### ISSUE TITLE
Completion for a project with multiple files

### ISSUE THREAD

**Issue by terhechte** [jpsim/SourceKitten#102]
Hey,

I'm trying to get completions for a project with at least two files. I.e. let's say I have
main.swift:
```
import Foundation

func main() {}
```

and
ExampleProtocols.swift
```
import Foundation

public protocol Identifiable {
    var name: String { get }
}

public protocol Accountable {
    var costs: Int { get set }
}
```

And I'm trying to run sourcekitten with
```
sourcekitten complete --text "struct A { let u: Int } ; let aa = A(u: 5) ; aa." --offset 48 --compilerargs -- "/path/to/main.swift /path/to/ExampleProtocols.swift -sdk sdk-path -c"
```

Then I get empty results. If I add a lot of compiler args (basically, everything that Xcode gives to swiftc during building) I get:

89723 Illegal instruction: 4

Is there even a way to run sourcekitten on a project with more than one file and get completions?

Regards & Thanks,
Benedikt

**Comment by jpsim** [comment]
The short answer is that SourceKit needs the same compiler arguments as `swiftc` would get in an Xcode project with those files, for which SourceKitten doesn't do for you automatically for multiple files.

I know that comment isn't of much help for you right now, but I'd need to spend more time with this problem to come up with a proper solution.

**Comment by terhechte** [comment]
I did some investigation, and found that those are the minimum required arguments for a very simple multi-file project (i.e. no different targets / dependencies, no external frameworks:

```
sourcekitten complete --text "struct A:Identifiable  { let name: String ; let u: Int } ; let aa = A(name: \"carl\", u: 5) ; aa." --offset 97 
--compilerargs -- "

-module-name FitureCompletion 
-sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk 
/Users/terhechte/Development/Cocoa/SourceKittenDaemon/SourceKittenDaemonTests/Fixtures/FitureCompletionTests/FitureCompletionTests/ExampleProtocols.swift 
/Users/terhechte/Development/Cocoa/SourceKittenDaemon/SourceKittenDaemonTests/Fixtures/FitureCompletionTests/FitureCompletion/main.swift 
-Xcc -I/Users/terhechte/Library/Developer/Xcode/DerivedData/FitureCompletionTests-elfludapdfytimbonfbtpehrgipu/Build/Intermediates/FitureCompletionTests.build/Debug-iphonesimulator/FitureCompletion.build/swift-overrides.hmap 
-Xcc -I/Users/terhechte/Library/Developer/Xcode/DerivedData/FitureCompletionTests-elfludapdfytimbonfbtpehrgipu/Build/Intermediates/FitureCompletionTests.build/Debug-iphonesimulator/FitureCompletion.build/FitureCompletion-all-target-headers.hmap 
-DDEBUG=1 "
```

What I'm currently left wondering about are those `.hmap` files. They can be generated via xcodebuild, but how often do they need to be generated? Probably not for every completion, but which code changes require a rebuilding of those files? Do you happen to know more about this?

Thanks!

**Comment by terhechte** [comment]
This is working fine now. Without the hmap files. I'm not sure what I did wrong in the examples above, but I've got it working now. Thanks though!
