### ISSUE TITLE
Completion limitations

### ISSUE THREAD

**Issue by keith** [jpsim/SourceKitten#113]
I noticed today that attempting to complete with SourceKitten like this:

```
sourcekitten complete --text "let a: St" --offset 8
```

Provides no results. I was just curious if you know what the limitations of completion coming from SourceKit are? The only completions I've seem to be able to get working is right after `.`.

**Comment by jpsim** [comment]
This has been brought up before in #86:

> > completion results do not always show up, as an example: sourcekitten complete --text "[1].m" --offset 4 works just fine and shows all of the available options, sourcekitten complete --text "[1].m" --offset 5 returns an empty array while it should return an option for the map function.
>
> This is actually a limitation in how SourceKit generates completion requests, so there's not much I can do for you there.

SourceKit only returns completion results in very specific locations, I think the logic is roughly "at the start of a statement" so immediately following a `.`, `(`, `)`, `;`, `:`, new line or backtick (I'm just guessing here, these might be wrong).

But, I'm so excited I can say this, you can read the SourceKit source code to find out more about how this works: https://github.com/apple/swift/blob/master/tools/SourceKit/lib/SwiftLang/SwiftCompletion.cpp

I haven't had much time to read through the SourceKit code just yet, so if you find out more about this, please share!

**Comment by keith** [comment]
Interesting! Thanks. This makes me want to go figure out how this works in Xcode as well.
