### ISSUE TITLE
Structure command ignoring return types

### ISSUE THREAD

**Issue by TadeasKriz** [jpsim/SourceKitten#138]
I was playing around with the SourceKitten and I found myself stuck on missing a return type information in the output of `sourcekitten structure --text "protocol pA { func test() -> String }"`. 

Is it missing in SourceKitten or the SourceKit itself?

**Comment by norio-nomura** [comment]
If you have builded Swift-OSS, you can confirm whether it missed in SourceKit or SourceKitten by using `sourcekitd-repl` (`sourcekitd-repl` is not included in weekly swift-2.2-SNAPSHOT):
```
% ${SWIFT_SOURCE_ROOT}/build/${build_subdir}/swift-macosx-x86_64/bin/sourcekitd-repl
(SourceKit) { "key.request": source.request.editor.open, "key.name": "SourceKitten#138", "key.sourcetext": "protocol pA { func test() -> String }"}
… Result from SourceKit will be following
```
I found a bug on SourceKit, filed [SR-489](https://bugs.swift.org/browse/SR-489) and used `sourcekitd-repl` on reproducing step.
I have deleted builded Swift-OSS, so I can't confirm by above step now.

**Comment by jpsim** [comment]
SourceKitten's `structure` command is a very thin wrapper around SourceKit, so if there's information you'd like to see in there, you'll likely have to implement it at the SourceKit level.

**Comment by TadeasKriz** [comment]
@jpsim But how does Jazzy get the return type then?

**Comment by jpsim** [comment]
Jazzy doesn't use the same approach as `structure` does. `structure` just parses Swift, whereas `docs` indexes and resolves all the symbols (it basically goes much further towards actually compiling the Swift code).

This is why SwiftLint still works with invalid Swift, but jazzy wouldn't.

**Comment by TadeasKriz** [comment]
@jpsim Thanks for clarification! The issue is indeed in SourceKit itself, I'll go ahead and report it.
