### ISSUE TITLE
SourceKitten doc Usage

### ISSUE THREAD

**Issue by qbraksa** [jpsim/SourceKitten#147]
Excuse the newbie question, but once we generate docs using `sourcekitten doc`, what would be the next step to have it rendered as HTML ? 

Or maybe it's NOT meant to be rendered as HTML ? in that case what is the JSON used for ?

**Comment by segiddins** [comment]
It's used by jazzy to generate HTML docs.

**Comment by qbraksa** [comment]
Thanks
