### ISSUE TITLE
Handle crash of SourceKitService

### ISSUE THREAD

**Issue by norio-nomura** [jpsim/SourceKitten#166]
On current implementation, SourceKittenFramework crashes on SourceKitService.
e.g.
```sh
% curl --silent https://raw.githubusercontent.com/apple/swift/master/validation-test/compiler_crashers_fixed/27947-swift-parser-parsebraceitems.swift |swiftlint lint --config ~/.swiftlint-test.yml --use-stdin
Loading configuration from '/Users/norio/.swiftlint-test.yml'
sourcekit: [1:connection-event-handler:3331: 0.0000] Connection interrupt
sourcekit: [1:pingService:3331: 0.0018] pinging service
[1]    92472 done                          curl --silent  | 
       92473 illegal hardware instruction  swiftlint lint --config ~/.swiftlint-test.yml --use-stdin
```
On that case, `fromSourceKit(_:)` returns `nil` and `Request.send()` crashes:
> fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by norio-nomura** [comment]
I want to fix this.
Should we add failable version of `send()` or make `send()` failable?

**Comment by jpsim** [comment]
Unfortunately once SourceKitService crashes, I haven't found a way to recover from that. Even if `send()` was fallable, the next request would also fail.

**Comment by jpsim** [comment]
Done in #169. Thanks @norio-nomura !

**Comment by norio-nomura** [comment]
:smile:
