### ISSUE TITLE
Use toolchain from xcode-select

### ISSUE THREAD

**Issue by jpsim** [jpsim/SourceKitten#167]

**Comment by norio-nomura** [comment]
As I saw https://github.com/jpsim/SourceKitten/pull/153#issuecomment-180985100, I feel we need doing this.

**Comment by norio-nomura** [comment]
did I misunderstand this?
I understood this as:
- `sourcekitten` loads `sourcekitd.framework` from directory tree that `xcode-select -p` pointing.  
- `xcode-select -p` are referred on runtime.  

I wrote #172 and #176 based on that…

**Comment by jpsim** [comment]
Yes, you understood this correctly and #172 & #176 seem like great solutions to this! I'm just trying to understand all the complexities required by the implementations in those PRs, and I'm starting to understand.

Looks like you did great work there! It's just taking me a long time to comprehend what all of it means.

**Comment by norio-nomura** [comment]
Thanks, I was relieved. :relieved:

**Comment by jpsim** [comment]
Done by @norio-nomura 👏 🎉
