### ISSUE TITLE
Full docstrings from completion request

### ISSUE THREAD

**Issue by johncsnyder** [jpsim/SourceKitten#187]
Currently, completion requests return a docBrief if it exists. Is it also possible to get the full docstring in JSON format ?

For frameworks where you have the full source and Xcode project, you could run the doc command to extract these, but what about built-in Frameworks within the sdk, such as Foundation or AppKit ? It would be useful for an autocompleter to be able to pull up this info.

**Comment by jpsim** [comment]
What do you mean by "full docstrings"? Do you mean the raw source code documentation comments like `///` and `/** */`? Those aren't provided by the SourceKit code completion response. You'd have to add that in SourceKit itself, not SourceKitten.

**Comment by johncsnyder** [comment]
Ok, I see, thanks !
