### ISSUE TITLE
SwiftKitten --- swift autocompleter for Sublime Text using SourceKitten

### ISSUE THREAD

**Issue by johncsnyder** [jpsim/SourceKitten#190]
No issue here !

Just wanted to let you know, I've created a Sublime package using SourceKitten, called [SwiftKitten](https://github.com/johncsnyder/SwiftKitten). I've submitted to it package control, so it should be available soon.

**Comment by jpsim** [comment]
Very cool! I'm definitely going to give this a shot to use myself. I just spread the good word: https://twitter.com/simjp/status/710942230026924032
