### ISSUE TITLE
Add Swift 2.2 Support

### ISSUE THREAD

**Issue by tamarnachmany** [jpsim/SourceKitten#196]
It looks like Source Kitten does not support Swift 2.2 and therefore doesn't support Jazzy Docs + other SourceKitten-dependent tools being run by devs with Xcode 7.3.

Seeing this error when generating Jazzy docs:

```
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:137:in `run_sourcekitten': Unable to find an Xcode with swift version 2.1.1. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

Thanks.

**Comment by tamarnachmany** [comment]
Actually what I am seeing is a Jazzy Swift support issue so I'm going to reopen it there. Thanks.

**Comment by sreedhargs89** [comment]
We are also facing same issue, could you please suggest the solution...?

**Comment by jpsim** [comment]
@sreedhargs89 please file a *detailed* bug report at https://github.com/realm/jazzy/issues/new
