### ISSUE TITLE
Support for associated values in enum

### ISSUE THREAD

**Issue by riccardoferretti** [jpsim/SourceKitten#199]
First of all, great job with this framework - it's really impressive!
I was trying to use it to inspect the structure of an enum, but I ran into an issue.
Given: 

```swift
enum Color {
  case None
  case RGB(Int, Int, Int)
}
```

SourceKitten recognizes the enum cases, but doesn't report on their associated types (in this case, the `Int` in the `RGB`).

Is there a plan to support that?

**Comment by jpsim** [comment]
That functionality would have to be added to SourceKit itself: https://github.com/apple/swift/tree/master/tools/SourceKit

**Comment by riccardoferretti** [comment]
Cool, now we just have to wait for Apple... 
Thanks for the quick reply!

**Comment by jpsim** [comment]
You could always contribute back that functionality to SourceKit yourself! Otherwise, I'm not sure  will be motivated to do this themselves.
