### ISSUE TITLE
Doesn't get necessary information on generic functions

### ISSUE THREAD

**Issue by artman** [jpsim/SourceKitten#201]
Consider the following protocol including a generic function:

```
protocol MyProtocol {
    func myGeneric<T>(param: () -> T)
}
```

The resulting JSON of running `sourcekitten structure` against the file doesn't hold any clue that the function is generic.

I'd expect there to be a key `key.generics` pointing to an array holding the value `T`, or have the method's name be `myGeneric<T>(_)` instead of `myGeneric(_)`.

**Comment by jpsim** [comment]
`sourcekitten structure` is just a thin wrapper around SourceKit, so it'd be better to file a radar or bug at https://bugs.swift.org if you want more features like this.
