### ISSUE TITLE
Use LlamaKit.Result throughout SourceKittenFramework

### ISSUE THREAD

**Issue by jpsim** [jpsim/SourceKitten#21]
This will allow returning errors directly from SourceKittenFramework instead of just logging them to stderr.

This should be straightforward enough that anyone with experience handling monadic results could do this. Feel free to file a PR, otherwise I'll get to it eventually.

**Comment by segiddins** [comment]
This will require replacing the use of fallible initializers with class factory methods

**Comment by robrix** [comment]
https://github.com/antitypical/Result would be the canonical one these days.

**Comment by jpsim** [comment]
Indeed.

**Comment by jpsim** [comment]
I really don't think this is important anymore.
