### ISSUE TITLE
Question:  How to determine return type in Swift method signature

### ISSUE THREAD

**Issue by sstadelman** [jpsim/SourceKitten#210]
Hi, thanks again for the assistance with the `index` command a couple weeks ago.  New question:  how would I derive the `return` parameter type `MetadataDocumentRequest`, in the following block?
```swift
func createMetadataDocumentRequest() -> MetadataDocumentRequest{
        return MetadataDocumentRequestImpl(serviceRoot: self.serviceRoot)
    }
```
Digging through the various `sourcekitten` commands, it seems the closest is from `structure`, where you can iterate through the `key.substructure`, and pick the last item, which in this case would match the `return` line, with type `MetadataDocumentRequestImpl`:
```json
{
  "key.kind" : "source.lang.swift.decl.function.method.instance",
  "key.offset" : 371,
  "key.nameoffset" : 376,
  "key.namelength" : 31,
  "key.bodyoffset" : 435,
  "key.bodylength" : 79,
  "key.accessibility" : "source.lang.swift.accessibility.internal",
  "key.substructure" : [
	{
	  "key.kind" : "source.lang.swift.expr.call",
	  "key.offset" : 451,
	  "key.nameoffset" : 451,
	  "key.namelength" : 27,
	  "key.bodyoffset" : 479,
	  "key.bodylength" : 29,
	  "key.length" : 58,
	  "key.substructure" : [
		{
		  "key.kind" : "source.lang.swift.decl.var.parameter",
		  "key.offset" : 479,
		  "key.nameoffset" : 479,
		  "key.namelength" : 11,
		  "key.bodyoffset" : 492,
		  "key.bodylength" : 16,
		  "key.length" : 29,
		  "key.name" : "serviceRoot"
		}
	  ],
	  "key.name" : "MetadataDocumentRequestImpl"
	}
  ],
  "key.name" : "createMetadataDocumentRequest()",
  "key.length" : 144
}, ...
```
But really, `MetadataDocumentRequestImpl` is an implementation of `MetadataDocumentRequest`, so the approach is not precise enough.  And, if the `return` is mid-block, I think all bets are off.

Is there a way to access the typeidentifier(?) value, after the `->` operator?

**Comment by sstadelman** [comment]
obviously there are a number of related questions in the issues list here.  will close while I chase down those threads.

**Comment by jpsim** [comment]
There's no easy way to do this. In fact, we hack our way around this exact use case when generating the dyld wrappers for clang & sourcekit in SourceKitten: https://github.com/jpsim/SourceKitten/blob/master/Source/SourceKittenFramework/Request.swift#L395-L429

**Comment by sstadelman** [comment]
thanks, i'll throw some breaks here and check it out
