### ISSUE TITLE
Is it possible to detect duplicate code using SourceKitten?

### ISSUE THREAD

**Issue by steve21124** [jpsim/SourceKitten#216]
if it is, how?

**Comment by jpsim** [comment]
You can find duplicate code just by doing regular text parsing. You don't need SourceKitten for that.

If you want to build a system that detects similar patterns, with heuristics accounting small variations in structure and naming, you could certainly do that using text parsing augmented by SourceKitten's `Structure` construct.

But SourceKitten doesn't ship a CLI command or API that will "show all duplicated code".
