### ISSUE TITLE
Break out `FormatCommand.swift` into a new package called swiftfmt ?

### ISSUE THREAD

**Issue by masters3d** [jpsim/SourceKitten#226]
I really like `swiftlint autocorrect --format` but I noticed that there are somethings (like removing whitespace) that don't really belong to the linter or source kitten. 

Do you think it would be better to break out or just contribute to the sourcekitten version? I was thinking gofmt for swift, informed by the swiftlint rules.

**Comment by jpsim** [comment]
gofmt for Swift, informed by SwiftLint rules, sounds exactly like `swiftlint autocorrect --format` to me.

You can choose to not trim whitespace (pass `false` to [`File.format(trimmingWhitespace: Bool, ...)`](https://github.com/jpsim/SourceKitten/blob/09a2fa4ea58c8c045afe4a6e564b67f8e5e96698/Source/SourceKittenFramework/File.swift#L54)).

We can expose a similar option for SwiftLint if you'd like.

**Comment by masters3d** [comment]
Perhaps I was thinking more of an implementation detail where a stand along package could provide the facilities to correct files (opposed to writing directly to the file on the correctable rule method) . This formater could also run stand alone and only provide white space formatting specific to swift. 

I could just make an alias for now :)

**Comment by masters3d** [comment]
https://github.com/apple/swift/pull/3439
swift-formater ;)
