### ISSUE TITLE
Syntax command returns byte offset, not character offset

### ISSUE THREAD

**Issue by WFT** [jpsim/SourceKitten#228]
`good.swift`:
```swift
// c
print(1)
```

`bad.swift`:
```swift
// ©
print(1)
```

Diffing the output of `sourcekitten syntax` I get this:
```diff
4c4
<     "length" : 5,
---
>     "length" : 6,
8c8
<     "offset" : 5,
---
>     "offset" : 6,
13c13
<     "offset" : 11,
---
>     "offset" : 12,
```

So the offsets/lengths seem to be thrown off by multibyte unicode sequences, which I don't think is the intended behavior (please correct me if I'm wrong!). 

I used SourceKitten version 0.13.0 from Homebrew. I reproduced this using both `--file` and `--text` command line options. It also seems to happen with `sourcekitten structure`, although I haven't really looked at that one.

This issue seems pretty similar to #114.

**Comment by jpsim** [comment]
> So the offsets/lengths seem to be thrown off by multibyte unicode sequences, which I don't think is the intended behavior (please correct me if I'm wrong!).

Yes you're wrong 😉. SourceKitten wraps SourceKit, which works entirely in byte offsets, so this is by design.

**Comment by WFT** [comment]
Oops. Good to know.

Is this documented somewhere that I overlooked?

**Comment by rogerluan** [comment]
This issue and doc was really helpful, thank you for documenting this 🙏 I was banging my head because I couldn't figure out why offsets were so off, but only sometimes... Why would SourceKit be doing this 😄 
Understanding that they are actually byte offsets was key 💪 thank you!
