### ISSUE TITLE
Issue when importing the sourcekittenframework

### ISSUE THREAD

**Issue by bolismauro** [jpsim/SourceKitten#229]
Hi everyone,
I plan to use SourceKitten for an internal refactoring tool and so I decided to start playing with SourceKitten.

I'm trying to embed SourceKitten in a Mac OSX project.
I tried two ways:
- compiling the sourcekitten repo and copy the framework in my project
- using carthage

In both cases I don't receive any compiler error, but when I run I receive the following error
```
dyld: Library not loaded: @rpath/SourceKittenFramework.framework/SourceKittenFramework
  Referenced from: /path/to/Library/Developer/Xcode/DerivedData/TestSourceKitten-boswdvsqhrllydemxggxbnstpnnj/Build/Products/Debug/TestSourceKitten
  Reason: image not found
```

I really don't understand what is going on.

The next step would be to import the framework into a playground to test it with ease, but this is another story.

What am I doing wrong?

**Comment by bolismauro** [comment]
Update, following this
https://github.com/realm/realm-cocoa/issues/975#issuecomment-58056819

I receive a new error
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /path/to/Library/Developer/Xcode/DerivedData/TestSourceKitten-boswdvsqhrllydemxggxbnstpnnj/Build/Products/Debug/SourceKittenFramework.framework/SourceKittenFramework
  Reason: image not found
Program ended with exit code: 9
```

**Comment by bolismauro** [comment]
I think I've fixed by changing the project type from terminal to cocoa app.
It seems that there are problems with that kind of project (not related to sourcekitten though)

**Comment by jpsim** [comment]
> It seems that there are problems with that kind of project (not related to sourcekitten though)

This is actually behaving as designed. Swift frameworks are dynamic, so you need to set the appropriate rpath's to find the framework and its dependencies (in this case the swift dylibs).

**Comment by dmitriyl** [comment]
> This is actually behaving as designed. Swift frameworks are dynamic, so you need to set the appropriate rpath's to find the framework and its dependencies (in this case the swift dylibs).

I'm not sure, but it seems a good idea to add this quote to README.md
