### ISSUE TITLE
Objective-C class properties cause SIGILL

### ISSUE THREAD

**Issue by frankus** [jpsim/SourceKitten#243]
Declaring a class property in Objective-C:

```
@property (class, readonly, nonatomic) Foo *shared;
```

and running sourcekitten (arguments of `doc -objc -- -x objective-c -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -I /path/to/project`) against it fails with a `terminated by signal SIGILL (Illegal instruction)` error.

**Comment by jpsim** [comment]
huh, interesting... thanks for reporting this

**Comment by jeremiegirault** [comment]
more info here: 
`private func accessorUSR(getter: Bool) -> String` checks for `py`
class properties contains a `cpy` tag
force unwrap causes the crash

**Comment by jeremiegirault** [comment]
more: proposed a fix in #285

**Comment by jpsim** [comment]
Merged in #291. Thanks to @jeremiegirault and @frankus for reporting 😄
