### ISSUE TITLE
Module support

### ISSUE THREAD

**Issue by vdka** [jpsim/SourceKitten#270]
I am working on a tool to parse the `.yaml` file produced by SwiftPM and use that to detect the argument's I need to pass to `sourcekitten`.

<details>
  <summary>Current call looks like this</summary>
```
sourcekitten complete --text '
import JSON

let json: JSON = ["key": true]

json.arr
' --offset 102 -- 
-j8 -D SWIFT_PACKAGE -Onone -g -enable-testing 
-F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks 
-target x86_64-apple-macosx10.10 
-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk 
-module-cache-path /Users/Ethan/tmp/swiftkitTest/.build/debug/ModuleCache 
-I /Users/Ethan/Sources/vdka/cj/.build/debug 
/Users/Ethan/tmp/swiftkitTest/Packages/JSON-0.12.1/Sources/JSON/Constants.swift 
/Users/Ethan/tmp/swiftkitTest/Packages/JSON-0.12.1/Sources/JSON/Expressible.swift 
/Users/Ethan/tmp/swiftkitTest/Packages/JSON-0.12.1/Sources/JSON/JSON.swift 
/Users/Ethan/tmp/swiftkitTest/Packages/JSON-0.12.1/Sources/JSON/JSONAccessors.swift 
/Users/Ethan/tmp/swiftkitTest/Packages/JSON-0.12.1/Sources/JSON/JSONConvertible.swift 
/Users/Ethan/tmp/swiftkitTest/Packages/JSON-0.12.1/Sources/JSON/JSONError.swift 
/Users/Ethan/tmp/swiftkitTest/Packages/JSON-0.12.1/Sources/JSON/JSONInitializable.swift 
/Users/Ethan/tmp/swiftkitTest/Packages/JSON-0.12.1/Sources/JSON/JSONOptionalExtensions.swift 
/Users/Ethan/tmp/swiftkitTest/Packages/JSON-0.12.1/Sources/JSON/JSONParser.swift 
/Users/Ethan/tmp/swiftkitTest/Packages/JSON-0.12.1/Sources/JSON/JSONRepresentable.swift 
/Users/Ethan/tmp/swiftkitTest/Packages/JSON-0.12.1/Sources/JSON/JSONSerializer.swift 
/Users/Ethan/tmp/swiftkitTest/Sources/main.swift
``` 
</details>

This work's fine until there are multiple packages. Working with Server Side Swift framework's there are a huge number of source files and when including them all `sourcekitten` times out or just doesn't respond in reasonable time.

I was wondering if it were possible to pass the flags to the already build `.swiftmodule` files somehow to get them to be used for completion?

**Comment by jpsim** [comment]
There's already some code to parse SPM's yaml build files that was added for SPM support to SourceKitten's `doc` command in #211. We could certainly share that with some of the other commands that benefit/require compiler arguments.

**Comment by vdka** [comment]
If the code is already largely written then I will have a look at implementing this soon. Should be fairly straight forward I imagine.
