### ISSUE TITLE
Xcode Source Editor Extensions and SourcekittenFramework

### ISSUE THREAD

**Issue by tkohout** [jpsim/SourceKitten#271]
Hello,
I am working on a Extension for code refactoring and I figured sourcekitten would be very useful for getting structure of the code.

I have hit a wall early on. It looks like extensions have to be sandboxed in order to run (though the documentation is quite scarce on the subject). Without it, the extension won't show up in the Xcode menu.

Sourcekitten seems to have problems with sandbox app as mentioned in https://github.com/jpsim/SourceKitten/issues/189 issue

on calling:
```
Structure(file: File(contents: invocation.buffer.completeBuffer))
```
i get 
```
xcrun: error: cannot be used within an App Sandbox.
```

My question is whether there is a way to work around it or whether the sourcekitten can't be used with the source editor extensions.

Cheers
Tomas

**Comment by norio-nomura** [comment]
You need to create xpc service for using SourceKittenFramework(SourceKit).
I did on https://github.com/norio-nomura/LinuxSupportForXcode/

**Comment by jpsim** [comment]
I certainly recommend @norio-nomura's approach to this. 👏

**Comment by tkohout** [comment]
Awesome, I had no idea you can do that. I will take a look in the code later. Does it mean I have to first start separate xpc service in order to use the extension? Or is there a way to start the xpc by the extension itself?

**Comment by norio-nomura** [comment]
I'm using `SourceKittenHelper.xpc` for calling SourceKitten(SourceKit) from outside of `LinuxSupport.appex`'s sandbox.

- Launched processes on using that:
<img width="404" alt="screenshot 2016-10-20 09 33 40" src="https://cloud.githubusercontent.com/assets/33430/19542350/6d6413b2-96a8-11e6-9cb1-c878f99e2e6e.png">

- Bundle structure:
```terminal.session
$ tree -d ~/Applications/LinuxSupportForXcode.app
/Users/norio/Applications/LinuxSupportForXcode.app
└── Contents
    ├── Frameworks
    │   ├── SWXMLHash.framework
    │   │   ├── Resources -> Versions/Current/Resources
    │   │   └── Versions
    │   │       ├── A
    │   │       │   ├── Resources
    │   │       │   └── _CodeSignature
    │   │       └── Current -> A
    │   ├── SourceKittenFramework.framework
    │   │   ├── Resources -> Versions/Current/Resources
    │   │   └── Versions
    │   │       ├── A
    │   │       │   ├── Resources
    │   │       │   └── _CodeSignature
    │   │       └── Current -> A
    │   └── Yaml.framework
    │       ├── Resources -> Versions/Current/Resources
    │       └── Versions
    │           ├── A
    │           │   ├── Resources
    │           │   └── _CodeSignature
    │           └── Current -> A
    ├── MacOS
    ├── PlugIns
    │   └── LinuxSupport.appex
    │       └── Contents
    │           ├── MacOS
    │           ├── Resources
    │           ├── XPCServices
    │           │   └── SourceKittenHelper.xpc
    │           │       └── Contents
    │           │           ├── MacOS
    │           │           └── _CodeSignature
    │           └── _CodeSignature
    ├── Resources
    │   └── Base.lproj
    └── _CodeSignature

38 directories
```

**Comment by tkohout** [comment]
Nice approach :). I managed to get it going, thank you very much.
