### ISSUE TITLE
Set APPLICATION_EXTENSION_API_ONLY for SourceKittenFramework and all its dependencies

### ISSUE THREAD

**Issue by jpsim** [jpsim/SourceKitten#299]
Which is necessary to use SourceKitten in an Xcode Source Editor Extension

**Comment by norio-nomura** [comment]
Application Extension requires sandboxing, AFAIK. Did you find any workaround other than using xpc?

**Comment by klaaspieter** [comment]
Is it possible to accidentally use the framework in a way that wouldn't pass review? Should that be documented somewhere?
