### ISSUE TITLE
Supporting changing the body of functions of Swift

### ISSUE THREAD

**Issue by prabodhprakash** [jpsim/SourceKitten#309]
Is there a way to change the existing function. For e.g. if I want to add few lines before the actual body of function starts, can I do it? If yes, how ? If no, what could be possible ways to develop it. Can this be also taken as enhancement, if not already available.

**Comment by jpsim** [comment]
You can definitely do this today. From the command line:

```
$ cat zero.swift
func zero() -> Int { return 0 }
$ sourcekitten structure --file zero.swift
{
  "key.diagnostic_stage" : "source.diagnostic.stage.swift.parse",
  "key.substructure" : [
    {
      "key.offset" : 0,
      "key.nameoffset" : 5,
      "key.accessibility" : "source.lang.swift.accessibility.internal",
      "key.length" : 31,
      "key.name" : "zero()",
      "key.bodyoffset" : 20,
      "key.kind" : "source.lang.swift.decl.function.free",
      "key.namelength" : 6,
      "key.bodylength" : 10
    }
  ],
  "key.offset" : 0,
  "key.length" : 32
}
```

You can see that the `zero()` function's body spans from byte offsets 20-30 (`bodyoffset` to `bodyoffset + bodylength`), so if you want to add some lines to it, just insert the lines at `20`.

```
$ sed 's/./&\
/20' zero.swift > out.swift
$ cat out.swift
func zero() -> Int {
 return 0 }
```

You can get the same kind of info by using SourceKittenFramework's `Structure` type.

**Comment by prabodhprakash** [comment]
Thank-you.

**Comment by prabodhprakash** [comment]
Does this always work? The 20 that you have mentioned, is 20th character in each line of the file. While the body offset provided is from starting of the file. Also, this code changes each line of the file, while only once may be required.

**Comment by jpsim** [comment]
The `sed` example I wrote was really just to satisfy your original question and show that SourceKitten provides you with all the information you need to perform your intended action.

What you do with that information is entirely up to you and outside of SourceKitten's purview. So I'll be closing this issue.
