### ISSUE TITLE
brew installer for linux

### ISSUE THREAD

**Issue by JotaPe** [jpsim/SourceKitten#314]
Idk you can make a way to install SourceKitten via Linuxbrew http://linuxbrew.sh/
I think is the exact way to do on MAC brew, but linux don't have xcodebuild so if you can make a brew install sourcekittenlinux thing gonna help me a lot and make the linuxbrew guys happy too

**Comment by jpsim** [comment]
The only way to install SourceKitten on Linux is to use the Swift Package Manager. Please see https://github.com/jpsim/SourceKitten#installation

**Comment by jpsim** [comment]
If you'd like to add Linuxbrew support, you're welcome to file a PR.
