### ISSUE TITLE
Can't generate docs with jazzy.sh

### ISSUE THREAD

**Issue by gubikmic** [jpsim/SourceKitten#339]
Didn't work out of the box for me.
("Could not parse compiler arguments from `xcodebuild` output." etc. Both logs are error free though)

However,
```
jazzy --xcodebuild-arguments -scheme,SourceKittenFramework
```
worked flawlessly.

Just want to share this in case it's not just me having this issue.

**Comment by jpsim** [comment]
Thanks for letting me know! Should be fixed in #340.
