### ISSUE TITLE
Merging output of structure and index commands

### ISSUE THREAD

**Issue by andriichernenko** [jpsim/SourceKitten#347]
I need output of both `structure` command (if, switch and other control statements, line count of methods and types) and `index` (type information, symbol references).

How difficult would it be to (reliably) merge the outputs of both commands (if possible at all)? 

`structure` references symbols by their human-readable names (e.g. `init(playerCount:)`), `index` contains USRs as well (`s:FV4Game4GamecFT11playerCountSi_S0_`. Btw, what is USR?). 

My first thought is to try and match symbols by their human-readable names, but seems like they can be different (for example, function arguments can either be included or omitted: `print(_:separator:terminator:)`, `print`). Also, I would need to track current scope when processing the `structure` output. I don't mind some manual work, but it would be nice to know about any potential pitfalls.

**Comment by jpsim** [comment]
It should be possible to merge both, probably most easily implemented within SourceKittenFramework itself rather than as a consumer of its public API.

---

Definition of USR in Swift's source `Lexicon.rst`: https://github.com/apple/swift/blame/master/docs/Lexicon.rst#L370-L375

> A Unified Symbol Resolution (USR) is a string that identifies a particular
> entity (function, class, variable, etc.) within a program. USRs can be
> compared across translation units to determine, e.g., when references in
> one translation refer to an entity defined in another translation unit.

**Comment by deville** [comment]
Okay then. I took a closer look at the names in structure output, and it seems that function arguments are omitted only for calls, not for declarations, so gathering fully qualified name from the declaration name and the names of parent scopes (e. g. `moduleName.TypeName.functionName(arg1:arg2)`) and using it to find the information in `index` output should work.

**Comment by jpsim** [comment]
Seems messier than it would need to be, but short of spending more time trying to do this myself, I don't have any concrete suggestions for you. Sorry.
