### ISSUE TITLE
Support Swift 3.1

### ISSUE THREAD

**Issue by felix91gr** [jpsim/SourceKitten#348]
Or else I'm compiling something wrong.

This is my environment:
* **OS:** Linux, Elementary OS (based on Ubuntu 16.04 LTS)
* **Toolchain:** Swift version 3.1-dev (LLVM a7c680da51, Clang 9772bf511a, Swift ac7b7f3777)

I compiled the toolchain myself.

And this is how I tried to compile SourceKitten:
1. **Ran this**:
```sh
sudo echo >> ~/.bashrc
sudo echo export LINUX_SOURCEKIT_LIB_PATH='/build/swift-3.1-DEVELOPMENT-SNAPSHOT-2017-03-19-a/usr/lib/sourcekitdInProc.framework/sourcekitdInProc' >> ~/.bashrc
```
2. **Relaunched the Terminal, cloned the repo and checkout-ed the latest release**:
```sh
git clone https://github.com/jpsim/SourceKitten
cd SourceKitten/
git checkout tags/0.17.0
```
3. **Tried to build it** (here it failed)
```console
$ swift build
Fetching https://github.com/Carthage/Commandant.git
Fetching https://github.com/drmohundro/SWXMLHash.git
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/norio-nomura/Clang_C.git
Fetching https://github.com/norio-nomura/SourceKit.git
Fetching https://github.com/antitypical/Result.git
Cloning https://github.com/antitypical/Result.git
Resolving https://github.com/antitypical/Result.git at 3.2.1
Cloning https://github.com/drmohundro/SWXMLHash.git
Resolving https://github.com/drmohundro/SWXMLHash.git at 3.0.3
Cloning https://github.com/Carthage/Commandant.git
Resolving https://github.com/Carthage/Commandant.git at 0.11.3
Cloning https://github.com/norio-nomura/SourceKit.git
Resolving https://github.com/norio-nomura/SourceKit.git at 1.0.1
Cloning https://github.com/jpsim/Yams.git
Resolving https://github.com/jpsim/Yams.git at 0.1.4
Cloning https://github.com/norio-nomura/Clang_C.git
Resolving https://github.com/norio-nomura/Clang_C.git at 1.0.2
error: the package has an unsupported layout, modulemap (/home/felix/Desktop/other-scripts/SourceKitten/Source/SourceKittenFramework/clang-c/module.modulemap) is not allowed to be mixed with sources
fix: move the modulemap inside include directory
```
I think either I did some step wrong, compiled or configured the Swift toolchain badly, or SourceKitten doesn't support Swift 3.1 yet :thinking:

**Comment by keith** [comment]
The problem here is that you need [this fix](https://github.com/jpsim/SourceKitten/commit/686d4523abd4e2e352dd6297fb95e2277c29bd59#diff-37ca2dd15ca0f6b1b49e78db084ef5b9), which happened after the 0.17.0 tag. I'm hoping we can convince @jpsim to tag a new release for this 😄

**Comment by jpsim** [comment]
Hi all, I haven't tried building SourceKitten with Xcode 8.3 final yet, and from what I can tell from #352, there are quite a few things that need updating to fully support Xcode 8.3. So let's keep this open until all those can be addressed.

**Comment by keith** [comment]
Sorry the part I'm mentioning applies for Swift 3.0 as well.
