### ISSUE TITLE
no such module Yams

### ISSUE THREAD

**Issue by 0xPr0xy** [jpsim/SourceKitten#353]
I'm trying to get sourceKitten to work with swift 3.1.
Using cocoapods to install cuckoo, which uses sourceKitten as a submodule.
When doing xcodebuild test in my project, sourceKitten swift3.1 branch throws this error:

```SourceKittenFramework/Module.swift:10:8: no such module 'Yams'```

**Comment by jpsim** [comment]
SourceKitten doesn't yet support Swift 3.1. Closing as a duplicate of #348
