### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by mikeKane** [jpsim/SourceKitten#362]
using the command brew install sourcekitten I get the following errors and output

=== CLEAN TARGET Result-Mac OF PROJECT Result WITH CONFIGURATION Debug ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **

The following build commands failed:
	Check dependencies
	Check dependencies
(2 failures)
make: *** [clean] Error 65
make: *** Waiting for unfinished jobs....

`2017-04-25 09:48:33 -0400

make
prefix_install
PREFIX=/usr/local/Cellar/sourcekitten/0.12.1
TEMPORARY_FOLDER=/private/tmp/sourcekitten-20170425-78753-1bzvy/SourceKitten.dst

rm -f "SourceKitten.pkg"
script/bootstrap
rm -rf "/private/tmp/sourcekitten-20170425-78753-1bzvy/SourceKitten.dst"
xcodebuild -workspace 'SourceKitten.xcworkspace' -scheme 'sourcekitten' DSTROOT=/private/tmp/sourcekitten-20170425-78753-1bzvy/SourceKitten.dst -configuration Debug clean
*** Updating submodules...
Build settings from command line:
    DSTROOT = /private/tmp/sourcekitten-20170425-78753-1bzvy/SourceKitten.dst

*** Bootstrapping Carthage/Checkouts/Commandant...
=== CLEAN TARGET SWXMLHash OSX OF PROJECT SWXMLHash WITH CONFIGURATION Debug ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

=== CLEAN TARGET Result-Mac OF PROJECT Result WITH CONFIGURATION Debug ===
Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **

The following build commands failed:
	Check dependencies
	Check dependencies
(2 failures)
make: *** [clean] Error 65
make: *** Waiting for unfinished jobs....

HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 2921795668970f9b5598037fc55940d29ba941d6
Last commit: 1 year ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 756f4fc39f2e88e5487dfce2e81ecadd10c0ef9a
Core tap last commit: 1 year ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.12.5-x86_64
Xcode: 8.3.2
CLT: 8.3.0.0.1.1490382677
GCC-4.2: build 0
Clang: 8.1 build 802
X11: N/A
System Ruby: 2.0.0-p648
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_65

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/git/bin:/usr/bin:/bin:/usr/sbin:/sbin
`

**Comment by norio-nomura** [comment]
Your Homebrew seems to be on April 22, 2016.
Could you try `brew update && brew install sourcekitten`?

**Comment by mikeKane** [comment]
Thanks!! worked perfect
