### ISSUE TITLE
What editors use SourceKitten (and use it well)?

### ISSUE THREAD

**Issue by felix91gr** [jpsim/SourceKitten#364]
Since [SourceKite](https://github.com/jinmingjian/sourcekite) is in hiatus for now, only SourceKitten is left as a layer from which to use SourceKit nicely.

I'm very interested in making a tutorial for the setup and use of Swift and Swift tooling on Linux (I made one [here](https://github.com/felix91gr/swift-linuxSetup/) right before 3.1 was released). In particular, for me it's very important that whatever editor you use, it includes error-checking and autocompletion. Is there something like that? That is also being maintained somewhat.

What I've found so far is this: [swiftkitten](https://packagecontrol.io/packages/SwiftKitten), but it looks like it's also in hiatus, so it's maybe not such a good idea to depend on it :thinking:

**Comment by felix91gr** [comment]
I guess if this doesn't exist, I'll have to slowly learn how to make an editor plugin from SourceKitten. But I won't be fast... I don't have experience in using lexers or code analizers (or whatever SK-like programs are)

**Comment by jpsim** [comment]
[SourceKittenDaemon](https://github.com/terhechte/SourceKittenDaemon) provides built-in editor integrations with Emacs, Atom and TextMate and is very actively maintained.

**Comment by felix91gr** [comment]
Oh, it really looks nice! And indeed, well maintained.

I have a question... 🤔 it says in the [Readme](https://github.com/terhechte/SourceKittenDaemon/blob/master/Readme.md) that it uses Taylor as a dependency. But I don't see any reference to the Taylor repo in the **package.swift** file. I guess the Readme is outdated, then? Or is there a magic dependency to Taylor that I haven't seen? 🤔🤔

**Comment by jpsim** [comment]
Looks like their readme might be outdated. Searching for "Taylor" in that repo only finds the readme reference: https://github.com/terhechte/SourceKittenDaemon/search?utf8=%E2%9C%93&q=taylor&type=

Anyway, I'll be closing this since hopefully that answered your question. If you have questions about SourceKittenDaemon, please ask them there 😄

**Comment by felix91gr** [comment]
Indeed. Thank you! 😊

**Comment by Dan2552** [comment]
If you're looking for one for Sublime Text, here's my project:
https://github.com/Dan2552/SourceKittenSubl
Features both autocomplete and mouseover docs.

> I don't have experience in using lexers or code analizers
Luckily SourceKit abstracts most of it away 😄

**Comment by felix91gr** [comment]
> ("Using it well" is a bit subjective though. Definitely happy for any PRs to improve!)

Hehe, indeed ^^

I'll keep an eye on your project! For the time being, I'm spending my tinker hours in [porting SourceKittenDaemon to Linux](https://github.com/terhechte/SourceKittenDaemon/issues/62). After I do that, I'll see what I do. 
Maybe we can plug SKD into Sublime and use what you've learned to do it "well" ;)

**Comment by lf-araujo** [comment]
Hey @Dan2552 , I am trying to use your addon on Linux, but the docs does not work for that platform, is that right? I managed to make sourcekitten work on Arch, but running `sourcekitten doc` causes the error:

```
 $  sourcekitten doc
Running xcodebuild
Fatal error: POSIX command failed with error: 2: file Foundation/Process.swift, line 515
Instrução ilegal (imagem do núcleo gravada)
```
Any ideas on how to fix this?

**Comment by jpsim** [comment]
Looks like you're probably hitting a limitation of swift corelibs Foundation on Arch. You could find the git revision for the Swift version you're using and look at [Process.swift](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/Process.swift) to know what function is either unimplemented or buggy on Arch.
