### ISSUE TITLE
[feature request] detect typealias in code

### ISSUE THREAD

**Issue by masters3d** [jpsim/SourceKitten#365]
file.swift
```swift
private typealias MyString = String
typealias MyInt = Int
```
`sourcekitten structure --file file.swift`
prints
```swift
{
  "key.diagnostic_stage" : "source.diagnostic.stage.swift.parse",
  "key.substructure" : [

  ],
  "key.offset" : 0,
  "key.length" : 58
}
```
I am not sure if this is a limitation of SourceKit but I'd like to be able to see typealiases.

**Comment by norio-nomura** [comment]
This is a limitation of SourceKit.
SourceKit's structure test's input including `typealias`:
https://github.com/apple/swift/blob/master/test/SourceKit/DocumentStructure/Inputs/access.swift#L93
The expected response does not have structure about `typealias`: https://github.com/apple/swift/blob/master/test/SourceKit/DocumentStructure/access_parse.swift.response

**Comment by masters3d** [comment]
Thanks!
