### ISSUE TITLE
.

### ISSUE THREAD

**Issue by jeffreyhanna** [jpsim/SourceKitten#367]
.

**Comment by jpsim** [comment]
We use @norio-nomura's [Docker SourceKit image](https://hub.docker.com/r/norionomura/sourcekit/) to test & run SourceKitten: https://github.com/jpsim/SourceKitten/blob/0.17.2/Makefile#L81-L85

You can see how it builds its version of Swift with `libsourcekitdInProc.so` in its repo: https://github.com/norio-nomura/docker-sourcekit-builder

All the commands are in https://github.com/norio-nomura/docker-sourcekit-builder/blob/master/Dockerfile

**Comment by norio-nomura** [comment]
The process building SourceKit has changed on master since Swift 3.1 does not need build twice. So, you need to refer https://github.com/norio-nomura/docker-sourcekit-builder/blob/302/Dockerfile for `swift-3.0.2-RELEASE`.

**Comment by jeffreyhanna** [comment]
Thanks for the quick response guys! 

I'm not familiar with docker, but seems fairly straightforward. Looks like this docker image was setup for Ubuntu 16.04, will I need to change things for Ubuntu 14.04?

**Comment by jpsim** [comment]
A Dockerfile for 14.04 is available here: https://github.com/norio-nomura/docker-sourcekit-builder/blob/master/Dockerfile-swift-14.04

It's basically just slightly different dependencies that need to be installed than for 16.04.

**Comment by jeffreyhanna** [comment]
Thank you!

**Comment by jeffreyhanna** [comment]
Sorry, just to be clear I should edit the dockerfile and replace:
```
COPY Dockerfile-swift-16.04 ${OUTPUT_DIR}/Dockerfile
```
with:
```
COPY Dockerfile-swift-14.04 ${OUTPUT_DIR}/Dockerfile
``` 
right?

**Comment by norio-nomura** [comment]
I have switched from 14.04 to 16.04 on https://github.com/norio-nomura/docker-sourcekit-builder/commit/5e2f7759efc752440d1df8b08b2cbe489f126d4f. That would be your help.

**Comment by norio-nomura** [comment]
😿
