### ISSUE TITLE
`swiftDeclaration` not generated for some Objective-C methods.

### ISSUE THREAD

**Issue by ainopara** [jpsim/SourceKitten#376]
When using SourceKitten to parse Objective-C headers, I found that some `SourceDeclaration` instance has a nil `swiftDeclaration` property.

After research, I found that is because SourceKit response of the cursorInfo request for those methods does not have a `SwiftDocKey.fullXMLDocs` key.
 (https://github.com/jpsim/SourceKitten/blob/master/Source/SourceKittenFramework/Clang%2BSourceKitten.swift#L212)

The swift interface of those methods can be extracted from `SwiftDocKey.annotatedDeclaration` key in the SourceKit response, so I tried to make a change and it works for me.

I'm not sure if this is a known issue in SourceKit that will be fixed in further release of Swift.

My commit: https://github.com/ainopara/SourceKitten/commit/e88e15370fd1ad67d8e2857da4e266b80e417b6b
My toolchain is from Xcode 8.3.2 (8E2002).

**Comment by jpsim** [comment]
Nice find! Would you be able to make a PR with the same commit from your fork? Thanks!

**Comment by ainopara** [comment]
`XMLElement` currently does not have the `recursiveText` property. I have made a PR there https://github.com/drmohundro/SWXMLHash/pull/131 .

**Comment by jpsim** [comment]
Fixed in #382.
