### ISSUE TITLE
[Question]Fetching trimmed down output using `structure` command

### ISSUE THREAD

**Issue by mamabusi** [jpsim/SourceKitten#408]
Is there a way to run the `structure` command on a swift file to generate trimmed down version of the output. For example: 

>       "key.substructure" : [
>             {
>               "key.namelength" : 0,
>               "key.nameoffset" : 0,
>               "key.kind" : "source.lang.swift.decl.enumcase",
>               "key.substructure" : [
>                 {
>                   "key.nameoffset" : 815,
>                   "key.accessibility" : "source.lang.swift.accessibility.internal",
>                   "key.length" : 6,
>                   "key.name" : "always",
>                   "key.kind" : "source.lang.swift.decl.enumelement",
>                   "key.namelength" : 6,
>                   "key.offset" : 815
>                 }
>               ],
>               "key.offset" : 810,
>               "key.length" : 11
>             },

The above is a snippet of the output and keys like offset, length, nameoffset etc. are something I do not require and wish it would not come as part of the output from `structure` command. 

Is there a way I could customise the output that will be generated by the `structure` command.

Thanks!

**Comment by jpsim** [comment]
Sure! Using the command line, you could use a tool like [jq](https://stedolan.github.io/jq/) to filter out keys you don't need.

Otherwise, using SourceKittenFramework, you could recursively remove the key/value pairs you don't want from the resulting dictionary.

**Comment by mamabusi** [comment]
@jpsim Thank you! That helps.
