### ISSUE TITLE
Can't build with Swift 4 on Linux

### ISSUE THREAD

**Issue by pushkarnk** [jpsim/SourceKitten#410]
I wish to use SourceKittenFramework with Swift 4's JSONDecoder on Linux. When I tried to simply run `swift build` against a fresh clone of SourceKitten I see a crash. I am using the latest Ubuntu 16.04 toolchain available on swift.org.

```
$swift --version
Swift version 4.0-dev (LLVM f53eb03c15, Clang 1757394ff0, Swift 27ea284484)
Target: x86_64-unknown-linux-gnu

$ swift build
Fetching https://github.com/Carthage/Commandant.git
Fetching https://github.com/drmohundro/SWXMLHash.git
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/norio-nomura/Clang_C.git
Fetching https://github.com/norio-nomura/SourceKit.git
Fetching https://github.com/antitypical/Result.git
Cloning https://github.com/drmohundro/SWXMLHash.git
Resolving https://github.com/drmohundro/SWXMLHash.git at 4.1.1
Cloning https://github.com/norio-nomura/SourceKit.git
Resolving https://github.com/norio-nomura/SourceKit.git at 1.0.1
Cloning https://github.com/Carthage/Commandant.git
Resolving https://github.com/Carthage/Commandant.git at 0.12.0
Cloning https://github.com/norio-nomura/Clang_C.git
Resolving https://github.com/norio-nomura/Clang_C.git at 1.0.2
Cloning https://github.com/jpsim/Yams.git
Resolving https://github.com/jpsim/Yams.git at 0.3.3
Cloning https://github.com/antitypical/Result.git
Resolving https://github.com/antitypical/Result.git at 3.2.3
Illegal instruction (core dumped)
```

Can someone help please?

**Comment by jpsim** [comment]
Thanks for letting us know about this. An "Illegal instruction" error while running `swift build` is a Swift Package Manager bug and should be filed at https://bugs.swift.org. Please share the SR number here once you've done that so we can follow along.

---

The latest Swift snapshot confirmed to work with SourceKitten on Linux is `2017-06-23-a`, as you can see here: https://github.com/jpsim/SourceKitten/blob/0.18.0/.travis.yml#L48

**Comment by jpsim** [comment]
I filed [SR-5595](https://bugs.swift.org/browse/SR-5595). FYI the snapshot from 4020170725a works fine.
