### ISSUE TITLE
Increase/remove -warn-long-function-bodies

### ISSUE THREAD

**Issue by marcelofabri** [jpsim/SourceKitten#415]
`-warn-long-function-bodies=200` is making the build fail on Xcode 9 beta 5 on my local machine (2017 MacBook Pro 15") and on [Travis CI](https://travis-ci.org/realm/SwiftLint/jobs/263931821). Might be worth filing a radar, since it's consistently slower for me in the recent beta.

We should either:
- Increase the limit
- Remove the limit
- Find out why it's taking so long to compile [that function](https://github.com/jpsim/SourceKitten/blob/036cb5042c55eef97cf59ae8670f6d44168fe6bc/Source/SourceKittenFramework/SourceDeclaration.swift#L66-L116) (and fix it).

**Comment by jpsim** [comment]
Yeah, it's really been bothering me lately too. It doesn't add much value anymore, and it's easy to turn on while locally debugging.

**Comment by jpsim** [comment]
Removed in 3f5c219.
