### ISSUE TITLE
Where to get libsourcekitdInProc.so for linux builds?

### ISSUE THREAD

**Issue by jverkoey** [jpsim/SourceKitten#420]
I'm not able to find it in the [Ubuntu 14.04 build of Swift 3.1.1](https://swift.org/builds/swift-3.1.1-release/ubuntu1404/swift-3.1.1-RELEASE/swift-3.1.1-RELEASE-ubuntu14.04.tar.gz).

As a result, I get the following failure when I attempt to run `sourcekitten format --file ...`:

```
fatal error: Loading libsourcekitdInProc.so failed
```

**Comment by norio-nomura** [comment]
`libsourcekitdInProc.so` is included in official package from Swift 4.0. Up to Swift 3.1 you need to build yourself, we are using [the docker image](https://hub.docker.com/r/norionomura/sourcekit/) we built.
