### ISSUE TITLE
Using request with text input

### ISSUE THREAD

**Issue by sidmani** [jpsim/SourceKitten#421]
How is the text supposed to be formatted in `sourcekitten request`? I have a yaml file:
```
key.request: source.request.editor.open.interface 
key.name: "47398610-AF42-4F99-B6F2-25A587793CEB" 
key.compilerargs:
- "-target"
- "arm64-apple-ios11.0"
- "-sdk"
- "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk"
- "-I"
- "-Xcc"
key.modulename: "UIKit.UIBezierPath"
key.toolchains:
- "com.apple.dt.toolchain.XcodeDefault"

```
and running `sourcekitten request --yaml test.yml` works fine. The readme says `request` accepts file or text arguments, so how do I pass it in as text? I tried escaping all the quotes and newlines like this:  
`sourcekitten request --yaml "key.request: source.request.editor.open.interface\n key.name: \"47398610-AF42-4F99-B6F2-25A587793CEB\"\n key.compilerargs:\n - \"-target\"\n - \"arm64-apple-ios11.0\"\n - \"-sdk\"\n - \"/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk\"\n - \"-I\"\n - \"-Xcc\"\n key.modulename: \"UIKit.UIBezierPath\"\n key.toolchains:\n - \"com.apple.dt.toolchain.XcodeDefault\""`  
But that fails. What's the correct format?

**Comment by jpsim** [comment]
This works:

```bash
$ sourcekitten request --yaml "key.compilerargs:
  - \"-target\"
  - \"arm64-apple-ios11.0\"
  - \"-sdk\"
  - \"/Applications/Xcode-9.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk\"
  - \"-I\"
  - \"-Xcc\"
key.modulename: \"UIKit.UIBezierPath\"
key.name: \"47398610-AF42-4F99-B6F2-25A587793CEB\"
key.request: source.request.editor.open.interface
key.toolchains:
  - \"com.apple.dt.toolchain.XcodeDefault\"
"
```
