### ISSUE TITLE
Default parameters

### ISSUE THREAD

**Issue by yonaskolb** [jpsim/SourceKitten#463]
Is it possible to work out if a function parameter has a default value using `SourceKittenFramework`? At the moment the contents of `Structure` doesn't seem to give an indication that a parameter is optional or not

**Comment by jpsim** [comment]
Unfortunately not. Since this is a limitation in SourceKit, do you think you could file a ticket at bugs.swift.org? I'd love to see this change myself. Thanks!

**Comment by yonaskolb** [comment]
I ended up just reading the string from `offset` to `length` and doing some string lookups around `=` 👍
