### ISSUE TITLE
Question: Dump whole framework as JSON?

### ISSUE THREAD

**Issue by hansemannn** [jpsim/SourceKitten#468]
Hey there!

Really great project, thank you for this! I have a question though: Is it possible to dump a *whole* framework as JSON? Including class definitions, selectors, parameters and docs? I know it may sounds weird, but I'd actually have a good use-case for it. Thanks!

**Comment by olbrichj** [comment]
Do you have the source? In that case, you could just use doc (as far as I understand). Though some of the requirements you would have to read from the return.  
If you don't you should use different tools, such as otool etc.

**Comment by hansemannn** [comment]
Thanks @olbrichj! Basically, I want to loop through all iOS system frameworks, so I'd have the public headers of it. But I am not sure if I can pass those to SourceKitten and receive back an AST of it. In case thats not possible, I will need to search for something else.

**Comment by olbrichj** [comment]
Sourcekitten will not work for this. Try classdump (https://github.com/nygard/class-dump).

But there are repos online which contain the headers of all iOS system frameworks e.g. https://github.com/nst/iOS-Runtime-Headers

You won't get an AST though. Maybe a disassambler like Hopper or IDA can help you to have a look at the internals.
