### ISSUE TITLE
swift build errror

### ISSUE THREAD

**Issue by hgabe** [jpsim/SourceKitten#470]
OS: Ubuntu 16.04 64-bit
Swift v4.0.3

Compile CYaml src/writer.c
Compile CYaml src/scanner.c
Compile CYaml src/reader.c
Compile CYaml src/parser.c
Compile CYaml src/emitter.c
Compile CYaml src/api.c
Compile Swift Module 'SWXMLHash' (2 sources)
Compile Swift Module 'Result' (2 sources)
Compile Swift Module 'Yams' (15 sources)
Compile Swift Module 'Commandant' (8 sources)
Compile Swift Module 'SourceKittenFramework' (34 sources)
Compile Swift Module 'sourcekitten' (10 sources)
Linking ./.build/x86_64-unknown-linux/debug/sourcekitten
/usr/bin/ld.gold: error: cannot find -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
error: terminated(1): /usr/bin/swift-build-tool -f /home/hgbs/temp/SourceKitten/.build/debug.yaml main

**Comment by jpsim** [comment]
I couldn't reproduce your issue. Could you please share steps to reproduce the problem?

Here's what I ran (with unrelated command output omitted with `[...]` for brevity):

```
$ doctl compute droplet create sourcekitten-470 --size 16gb --image ubuntu-16-04-x64 --region sfo2 --ssh-keys XXXXXXXX
ID          Name                Public IPv4    Private IPv4    Public IPv6    Memory    VCPUs    Disk    Region    Image                 Status    Tags    Features    Volumes
80283196    sourcekitten-470                                                  16384     8        160     sfo2      Ubuntu 16.04.3 x64    new
$ doctl compute ssh sourcekitten-470
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-112-generic x86_64)
[...]
$ apt-get update
[...]
$ apt-get install -y clang libblocksruntime0 libcurl4-openssl-dev
[...]
$ curl https://swift.org/builds/swift-4.0.3-release/ubuntu1604/swift-4.0.3-RELEASE/swift-4.0.3-RELEASE-ubuntu16.04.tar.gz \
    | tar xz --directory / --strip-components=1
[...]
$ git clone https://github.com/jpsim/SourceKitten.git
[...]
$ cd SourceKitten/
$ swift test
Fetching https://github.com/Carthage/Commandant.git
Fetching https://github.com/drmohundro/SWXMLHash.git
[...]
Compile CYaml src/scanner.c
Compile CYaml src/reader.c
Compile CYaml src/parser.c
Compile CYaml src/writer.c
Compile CYaml src/emitter.c
Compile CYaml src/api.c
[...]
Compile Swift Module 'sourcekitten' (10 sources)
Linking ./.build/x86_64-unknown-linux/debug/sourcekitten
Compile Swift Module 'SourceKittenPackageTests' (1 sources)
Linking ./.build/x86_64-unknown-linux/debug/SourceKittenPackageTests.xctest
Test Suite 'All tests' started at 2018-01-27 00:02:55.970
[...]
Test Suite 'All tests' passed at 2018-01-27 00:03:09.026
   Executed 42 tests, with 0 failures (0 unexpected) in 13.05 (13.05) seconds
```

**Comment by jpsim** [comment]
I think you're missing some prerequisites for Swift on Linux. Run this and try building again:

```
apt-get install -y clang libblocksruntime0 libcurl4-openssl-dev
```

**Comment by hgabe** [comment]
Cloned the SourceKitten git repositorie and run the swift build command

**Comment by hgabe** [comment]
I used swift build -v command and got this (use -v to see invocation)

swift build -v
lsb_release -r
which clang
/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/4 -lPackageDescription -swift-version 4 -I /usr/lib/swift/pm/4 -sdk / /home/hgbs/SourceKitten/Package.swift -fileno 6
/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/4 -lPackageDescription -swift-version 4 -I /usr/lib/swift/pm/4 -sdk / /home/hgbs/SourceKitten/.build/checkouts/Commandant.git-8197225550774909956/Package.swift -fileno 6
/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/4 -lPackageDescription -swift-version 4 -I /usr/lib/swift/pm/4 -sdk / /home/hgbs/SourceKitten/.build/checkouts/SWXMLHash.git-3127419067166814637/Package.swift -fileno 6
/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/4 -lPackageDescription -swift-version 4 -I /usr/lib/swift/pm/4 -sdk / /home/hgbs/SourceKitten/.build/checkouts/Yams.git-7598601401925675959/Package.swift -fileno 6
/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/3 -lPackageDescription -swift-version 3 -I /usr/lib/swift/pm/3 -sdk / /home/hgbs/SourceKitten/.build/checkouts/Clang_C.git-5157669112196895570/Package.swift -fileno 6
/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/3 -lPackageDescription -swift-version 3 -I /usr/lib/swift/pm/3 -sdk / /home/hgbs/SourceKitten/.build/checkouts/SourceKit.git--6697804665461616562/Package.swift -fileno 6
/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/3 -lPackageDescription -swift-version 3 -I /usr/lib/swift/pm/3 -sdk / /home/hgbs/SourceKitten/.build/checkouts/Result.git-5130548998162330795/Package.swift -fileno 6
/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/4 -lPackageDescription -swift-version 4 -I /usr/lib/swift/pm/4 -sdk / /home/hgbs/SourceKitten/.build/checkouts/Quick.git--8149616954887314567/Package@swift-4.swift -fileno 6
/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/3 -lPackageDescription -swift-version 3 -I /usr/lib/swift/pm/3 -sdk / /home/hgbs/SourceKitten/.build/checkouts/Nimble.git-6552992902862989241/Package.swift -fileno 6
/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/3 -lPackageDescription -swift-version 3 -I /usr/lib/swift/pm/3 -sdk / /home/hgbs/SourceKitten/.build/checkouts/Nimble.git-6552992902862989241/Package.swift -fileno 6
/usr/bin/swift-build-tool -f /home/hgbs/SourceKitten/.build/debug.yaml main -v
/usr/bin/swiftc -target 'x86_64-unknown-linux' -sdk / -g -L '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug' -o '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/sourcekitten' -module-name sourcekitten -emit-executable -Xlinker '-rpath=$ORIGIN' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Commandant.build/Argument.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Commandant.build/ArgumentParser.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Commandant.build/ArgumentProtocol.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Commandant.build/Command.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Commandant.build/Errors.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Commandant.build/HelpCommand.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Commandant.build/Option.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Commandant.build/Switch.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/CYaml.build/src/api.c.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/CYaml.build/src/emitter.c.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/CYaml.build/src/parser.c.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/CYaml.build/src/reader.c.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/CYaml.build/src/scanner.c.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/CYaml.build/src/writer.c.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Result.build/Result.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Result.build/ResultProtocol.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/sourcekitten.build/CompleteCommand.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/sourcekitten.build/DocCommand.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/sourcekitten.build/Errors.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/sourcekitten.build/FormatCommand.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/sourcekitten.build/IndexCommand.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/sourcekitten.build/main.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/sourcekitten.build/StructureCommand.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/sourcekitten.build/SyntaxCommand.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/sourcekitten.build/VersionCommand.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/sourcekitten.build/YamlRequestCommand.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/Clang+SourceKitten.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/ClangTranslationUnit.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/CodeCompletionItem.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/Dictionary+Merge.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/Documentation.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/File.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/JSONOutput.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/Language.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/library_wrapper_CXString.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/library_wrapper_Documentation.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/library_wrapper_Index.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/library_wrapper_sourcekitd.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/library_wrapper.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/LinuxCompatibility.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/Module.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/ObjCDeclarationKind.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/OffsetMap.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/Parameter.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/Request.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/SourceDeclaration.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/SourceLocation.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/StatementKind.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/String+SourceKitten.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/Structure.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/SwiftDeclarationKind.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/SwiftDocKey.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/SwiftDocs.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/SwiftLangSyntax.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/SyntaxKind.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/SyntaxMap.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/SyntaxToken.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/Text.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/Version.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SourceKittenFramework.build/Xcode.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SWXMLHash.build/SWXMLHash.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/SWXMLHash.build/SWXMLHash+TypeConversion.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Constructor.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Decoder.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Emitter.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Encoder.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Mark.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Node.Mapping.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Node.Scalar.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Node.Sequence.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Node.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Parser.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Representer.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Resolver.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/String+Yams.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/Tag.swift.o' '/home/hgbs/SourceKitten/.build/x86_64-unknown-linux/debug/Yams.build/YamlError.swift.o'
/usr/bin/ld.gold: error: cannot find -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
error: terminated(1): /usr/bin/swift-build-tool -f /home/hgbs/SourceKitten/.build/debug.yaml main -v


It ask which clang and I am using
clang version 5.0.1-svn319952-1~exp1 (branches/release_50)
Target: x86_64-pc-linux-gnu
Thread model: posix

**Comment by jpsim** [comment]
Based on this error message:

```
/usr/bin/ld.gold: error: cannot find -lstdc++
```

It sure looks like you're missing some prerequisites for Swift on Linux.

Could you please run this and try building again:

```
apt-get install -y clang libblocksruntime0 libcurl4-openssl-dev
```

**Comment by hgabe** [comment]
Solved installed pop_os swift build worked

Fetching https://github.com/Carthage/Commandant.git
Fetching https://github.com/drmohundro/SWXMLHash.git
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/norio-nomura/Clang_C.git
Fetching https://github.com/norio-nomura/SourceKit.git
Fetching https://github.com/antitypical/Result.git
Fetching https://github.com/Quick/Nimble.git
Fetching https://github.com/Quick/Quick.git
Cloning https://github.com/norio-nomura/Clang_C.git
Resolving https://github.com/norio-nomura/Clang_C.git at 1.0.2
Cloning https://github.com/norio-nomura/SourceKit.git
Resolving https://github.com/norio-nomura/SourceKit.git at 1.0.1
Cloning https://github.com/antitypical/Result.git
Resolving https://github.com/antitypical/Result.git at 3.2.4
Cloning https://github.com/Carthage/Commandant.git
Resolving https://github.com/Carthage/Commandant.git at master
Cloning https://github.com/Quick/Quick.git
Resolving https://github.com/Quick/Quick.git at 1.2.0
Cloning https://github.com/drmohundro/SWXMLHash.git
Resolving https://github.com/drmohundro/SWXMLHash.git at 4.2.5
Cloning https://github.com/Quick/Nimble.git
Resolving https://github.com/Quick/Nimble.git at 7.0.2
Cloning https://github.com/jpsim/Yams.git
Resolving https://github.com/jpsim/Yams.git at 0.5.0
Compile CYaml src/writer.c
Compile CYaml src/scanner.c
Compile CYaml src/reader.c
Compile CYaml src/parser.c
Compile CYaml src/emitter.c
Compile CYaml src/api.c
Compile Swift Module 'SWXMLHash' (2 sources)
Compile Swift Module 'Result' (2 sources)
Compile Swift Module 'Yams' (15 sources)
Compile Swift Module 'Commandant' (8 sources)
Compile Swift Module 'SourceKittenFramework' (34 sources)
Compile Swift Module 'sourcekitten' (10 sources)
Linking ./.build/x86_64-unknown-linux/debug/sourcekitten

**Comment by jpsim** [comment]
okie
