### ISSUE TITLE
SPM build fails with "revisioned dependencies" error

### ISSUE THREAD

**Issue by lvsti** [jpsim/SourceKitten#478]
I'm using SourceKittenFramework in my [project](https://github.com/lvsti/Bridgecraft) and today the 0.19.0 release has broken the SPM build:

```
$ swift build -c release -Xswiftc -static-stdlib
[...]
Fetching https://github.com/jpsim/SourceKitten.git
[...]
error: the package https://github.com/jpsim/SourceKitten.git @ 0.19.0 contains revisioned dependencies:
    https://github.com/Carthage/Commandant.git @ master
error: product dependency 'SourceKittenFramework' not found
[...]
```

The culprit is probably this line: https://github.com/jpsim/SourceKitten/blob/master/Package.swift#L11

Could you please pin an appropriate version for Commandant?

**Comment by jpsim** [comment]
> Could you please pin an appropriate version for Commandant?

For that I first had to _cut_ a release of Commandant, which hadn't been done in nearly a year, so I just did that earlier today: https://github.com/Carthage/Commandant/releases/tag/0.13.0

Now I'm in the process of updating SourceKitten to point to that release, but it's taking more time than expected, especially as I'm doing this in parallel with my worky-work from my jobby-job.

Hang tight, this should be done soon enough.

**Comment by lvsti** [comment]
awesome, thanks!
