### ISSUE TITLE
Problem locating the source kit shared library on linux

### ISSUE THREAD

**Issue by mhovan** [jpsim/SourceKitten#513]
I was just attempting to try out the SwiftLint project (which uses SourceKitten) on Linux but was having trouble loading the `libsourcekitdInProc.so`. It turns out I had a typo in my `LINUX_SOURCEKIT_LIB_PATH` environment variable name. But... That typo uncovered 
what might be a tiny issue in how `library_wrapper.swift` attempts to create a fall-back path to the shared lib directory.  I'll put up a pull request with my proposed fix (only tested on a recent Ubuntu release).

Pull Request #514 submitted with proposed (tiny) fix.

**Comment by jpsim** [comment]
Fixed in #514.
