### ISSUE TITLE
Sourcekitten can't find the standard libraries in Archlinux

### ISSUE THREAD

**Issue by lf-araujo** [jpsim/SourceKitten#524]
Dear devs,

Thanks for the software.

I wanted to report that it is not running neither under Ubuntu nor under Archlinux. Any attempt to complete leads to the very uniformative error:

`─λ ./.build/x86_64-unknown-linux/debug/sourcekitten complete
<unknown>:0: error: unable to load standard library for target 'x86_64-unknown-linux-gnu`

Any suggestion on how to debug this?

Many thanks.

**Comment by jpsim** [comment]
Did you build this binary on the same system? Looks like it can’t find the Swift standard library.

We continuously run unit tests on Ubuntu in CI so it’s very unlikely that things are generally not working on that platform.

**Comment by lf-araujo** [comment]
This was tested in the same machine, Ubuntu version 17.10. I recently installed archlinux after latest ubuntu upgrade failing. Note that someone else also had the same error on Ubuntu as per [this](https://stackoverflow.com/questions/44772911/error-unable-to-load-standard-library-for-target-x86-64-unknown-linux-gnu-usi) question on SO.

There must be something I am doing wrong (since you have CI for this repo), where should the Swift standard library be located in a Linux filesystem?

**Comment by kirbyfan64** [comment]
What's the output of running:

```
file /usr/lib/libsourcekitdInProc.so
```

**Comment by lf-araujo** [comment]
```
 $  file /usr/lib/libsourcekitdInProc.so
/usr/lib/libsourcekitdInProc.so: symbolic link to ../lib/swift/lib/libsourcekitdInProc.so
```

**Comment by lf-araujo** [comment]
The solution:

Configure the environment variable `LINUX_SOURCEKIT_LIB_PATH` for the entire system.

This can be done adding `export LINUX_SOURCEKIT_LIB_PATH=/usr/lib/swift/lib` to `/etc/profile.d/sourcekitten.sh`.
