### ISSUE TITLE
Test/Build Failure in Ubuntu 18.04 LTS with Swift 4.1.2

### ISSUE THREAD

**Issue by sus007** [jpsim/SourceKitten#541]
1. **OS**: Ubuntu 18.04 LTS x86_64
2. **Swift**: [**Swift version 4.2-dev (LLVM d6832022e4, Clang 1b52d77eec, Swift f4359b73f9)**](https://swift.org/builds/development/ubuntu1610/swift-DEVELOPMENT-SNAPSHOT-2018-07-05-a/swift-DEVELOPMENT-SNAPSHOT-2018-07-05-a-ubuntu16.10.tar.gz)
3. **Clang** : clang version **6.0.1**-svn334776-1~exp1~20180627155658.89 (branches/release_60)

I followed all the steps described by @jpsim as in this [**comment**](https://github.com/jpsim/SourceKitten/issues/470#issuecomment-360940287) to build SourceKitten in a Linux Machine. Still, I'm getting 2 failures at the end of `swift test` execution.
![image](https://user-images.githubusercontent.com/7630815/42379363-20674f78-814a-11e8-8935-48b578bda828.png)

### Failures :point_down: 
![image](https://user-images.githubusercontent.com/7630815/42379529-9df61a32-814a-11e8-9c9a-4d0be6259329.png)

> I know the failures clearly mention about the specific version i.e >4.1.50 , therefore, I also tried building/testing SourceKitten by downgrading Swift to <= 4.1.50. But, that resulted in a total of 11 further errors. 

Edit: Proper Swift & Clang Version

**Comment by norio-nomura** [comment]
`swift-DEVELOPMENT-SNAPSHOT-2018-07-05-a` is not Swift 4.1.2.
SourceKitten can not pass tests yet with Swift 4.2 or later.

**Comment by sus007** [comment]
@norio-nomura :up:  :eyes: 
> _I know the failures clearly mention about the specific version i.e >4.1.50 , therefore, **I also tried building/testing SourceKitten by downgrading Swift to <= 4.1.50. But, that resulted in a total of 11 further errors**_.
