### ISSUE TITLE
SwiftDoc does not extract all comment text

### ISSUE THREAD

**Issue by pkasson** [jpsim/SourceKitten#556]
I have noticed that unless a comment block starts with typical markdown syntax (i.e. /** versus either // or just /*), then SwiftDoc does not locate it in the process.

Is there a simple way to configure the processor to find all comments, regardless of syntax ?

**Comment by jpsim** [comment]
A comment in Swift starting with `//` is a _line comment_, not a doc comment. `///` is a doc comment and so is `/** ... */`. See https://nshipster.com/swift-documentation/ for reference.

**Comment by pkasson** [comment]
Thanks for the clarification.
