### ISSUE TITLE
Ubuntu 18.04 Swift Build Warning

### ISSUE THREAD

**Issue by hgabe** [jpsim/SourceKitten#564]
OS  Ubuntu 18.04
Swift 4.2.1
Cland: clang 6.0.0

Compile Clang_C Clang_C.m
Compile SourceKit SourceKit.m
Compile CYaml src/writer.c
Compile CYaml src/scanner.c
Compile CYaml src/reader.c
Compile CYaml src/parser.c
Compile CYaml src/emitter.c
Compile CYaml src/api.c
Compile Swift Module 'Result' (4 sources)
Compile Swift Module 'SWXMLHash' (3 sources)
Compile Swift Module 'Yams' (16 sources)
/home/aesop/SourceKitten/.build/checkouts/SWXMLHash.git--5657512651025603501/Source/SWXMLHash.swift:430:33: warning: conditional cast from 'Error' to 'NSError' always succeeds
        if let err = parseError as? NSError {
                                ^
Compile Swift Module 'Commandant' (9 sources)
Compile Swift Module 'SourceKittenFramework' (36 sources)
Compile Swift Module 'sourcekitten' (11 sources)
Linking ./.build/x86_64-unknown-linux/debug/sourcekitten

**Comment by jpsim** [comment]
Merged and released upstream
