### ISSUE TITLE
Include directory suffixed with .swift causes doc command to fail

### ISSUE THREAD

**Issue by 1ec5** [jpsim/SourceKitten#574]
The Mapbox Navigation SDK for iOS runs `jazzy` passing in [this podspec](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation-Documentation.podspec) as `--podspec`. Among the errors we’re working through in mapbox/mapbox-navigation-ios#1795 is this one caused by the dependency on the [MapboxDirections.swift](https://github.com/mapbox/MapboxDirections.swift/) pod:

```
Could not read contents of `/var/folders/cl/8cgpg37n5cl78pjkbpgml94w0000gn/T/jazzy20190128-87912-1r7txvvMapboxNavigation-Documentation/build/Release-iphoneos/MapboxDirections.swift`
Could not parse `MapboxDirections.swift`. Please open an issue at https://github.com/jpsim/SourceKitten/issues with the file contents.
```

CocoaPods places the pod’s downloaded framework inside a MapboxDirections.swift directory. jazzy passes the framework root’s path to `xcodebuild` as an include directory (`-I`). But the “.swift” suffix in the directory name causes SourceKitten to detect the folder as a Swift file:

https://github.com/jpsim/SourceKitten/blob/4a0f386df56aa40c596b92116c1e914edbd90bd4/Source/SourceKittenFramework/String+SourceKitten.swift#L453-L455

So then `sourcekitten doc` fails because `Module.docs` thinks it needs to parse a “MapboxDirections.swift” file for documentation:

https://github.com/jpsim/SourceKitten/blob/4a0f386df56aa40c596b92116c1e914edbd90bd4/Source/SourceKittenFramework/Module.swift#L81 https://github.com/jpsim/SourceKitten/blob/4a0f386df56aa40c596b92116c1e914edbd90bd4/Source/SourceKittenFramework/File.swift#L64-L69

/cc @JThramer

**Comment by jpsim** [comment]
Oops, you were right, the `isFile` helper is incorrect and also returns `true` for directories. Your fix at #575 looks good at a glance, we just have to figure out why it's failing CI.
