### ISSUE TITLE
When source has unicode characters, index for structure items is off by n number of unicode characters

### ISSUE THREAD

**Issue by miwand** [jpsim/SourceKitten#608]
Hi @jpsim, first of all, great project!. This is related to this issue - https://github.com/jpsim/SourceKitten/issues/560, but since the previous person had abandoned it I have decided to open a new issue with more details.

Purpose: 
I am trying to extract the string values in the getText function.

Problem: 
When adding unicode characters such as ° it increases the index of structure items by x for a unicode. It is x, because I have tried two different unicode characters and got different results. For ° I get +1 but for  I get +2 per unicode character. I am adding these characters through Option + shift + 8 or Option + shift + k

The command that I run for this is SourceKitten structure --file filename.swift. The values that I look at are the last body offset of the first and second substructure. So I checked the key length of the structure and I see 324 characters, but if I print out the contents of the file using `try String(contentsOfFile: filePath, encoding: .utf8)` I get 322 characters. Am I doing something wrong here? Also, get the same result when using `let file 
 = File(path: file.relativePath)` and then making a structure out of that file using `try? Structure(file: file)`. Finally using the file.contents to pick out the string using the body offset and length provided.
```
import Foundation

public func getText(_ valueOne: String, _ valueTwo: String) -> String {
    return valueOne + valueTwo
}

struct A {
    let x = getText("Some x Value", "Some other x value")
    let specialCharacter = getText("Special degrees°", "Special°")
    let y = getText("Some y Value", "Some other y value")
}
```

**Comment by jpsim** [comment]
The offsets used by SourceKitten are the same as the ones used by SourceKit, and they correspond to byte offsets into the file rather than character counts.

**Comment by miwandn** [comment]
Ah ok, that makes sense now. Thanks a ton!

Solution: Used index on data instead of the contents

 Issue can be closed
