### ISSUE TITLE
SourceKitten don't return "key.parsed_declaration" value

### ISSUE THREAD

**Issue by incetro** [jpsim/SourceKitten#620]
I have a file with the given content:

```
public class Entity {}

```

And I do this:
```
let url = URL(string: "Path for the file")!
print(SwiftDocs(file: File(path: url.absoluteString)!, arguments: ["-j4", url.absoluteString])!)
```

I have got information about my code but there is no "key.parsed_declaration" value:
```
{
  "Path for the file" : {
    "key.diagnostic_stage" : "source.diagnostic.stage.swift.parse",
    "key.length" : 23,
    "key.offset" : 0,
    "key.substructure" : [
      {
        "key.accessibility" : "source.lang.swift.accessibility.public",
        "key.attributes" : [
          {
            "key.attribute" : "source.decl.attribute.public",
            "key.length" : 6,
            "key.offset" : 0
          }
        ],
        "key.bodylength" : 0,
        "key.bodyoffset" : 21,
        "key.kind" : "source.lang.swift.decl.class",
        "key.length" : 15,
        "key.name" : "Entity",
        "key.namelength" : 6,
        "key.nameoffset" : 13,
        "key.offset" : 7,
        "key.runtime_name" : "_TtC4main6Entity"
      }
    ]
  }
}
```

Do you have any ideas why I can't get "key.parsed_declaration" value?

**Comment by johnfairh** [comment]
All of the CursorInfo fields are missing. This means Swift couldn't typecheck the code.

I think you're trying to reimplement  `sourcekitten --single-file-mode` -- looks to me as though Swift now always requires an SDK even if Foundation isn't imported.  This works for me:

```bash
sourcekitten doc --single-file Test.swift -- -j4 -sdk $(xcrun --show-sdk-path -sdk macosx) $(pwd)/Test.swift
```

Once you have that working you should be able to chip out the code fragment you want.

**Comment by incetro** [comment]
@johnfairh please last question.. 
if I use my code like ```SwiftDocs(file: File(path: url.absoluteString)!, arguments: ["-j4", url.absoluteString])``` (SourceKitten through SPM) how should I use your advice with all constructions you've showed me in the answer above?

**Comment by johnfairh** [comment]
I don't really understand: you need to pass in the arguments I showed (or whatever SDK you want to use).  You are using the same codepath that `--single-file` is, [here](https://github.com/jpsim/SourceKitten/blob/be4af15681951a090cf92c1ce345549cb15c536b/Source/sourcekitten/DocCommand.swift#L90).

**Comment by incetro** [comment]
@johnfairh I just want to understand how to pass your string ```sourcekitten doc --single-file Test.swift -- -j4 -sdk $(xcrun --show-sdk-path -sdk macosx) $(pwd)/Test.swift``` into the SwiftDocs initializer?

**Comment by incetro** [comment]
@johnfairh Maybe this code example can help to understand..
```
public func run() throws {
        let filepath = "/Users/incetro/Desktop/Test.swift"
        let url = URL(fileURLWithPath: filepath)
        let content = try String(contentsOf: url)
        print(content)
        print(SwiftDocs(file: File(path: filepath)!, arguments: [
            "-j4",
            "-sdk",
            "$(xcrun --show-sdk-path -sdk macosx) $(pwd)\(filepath)",
//            "-sdk $(xcrun --show-sdk-path -sdk macosx) $(pwd)\(filepath)"
//            "$(xcrun --show-sdk-path -sdk macosx)",
//            "$(pwd)\(filepath)"
        ])!)
    }
```

The file's `Test.swift` content:
```
func abc(
   argument: Int
) -> String
```

But output doesn't have `key.parsed_declaration`:

```
{
  "\/Users\/incetro\/Desktop\/Test.swift" : {
    "key.diagnostic_stage" : "source.diagnostic.stage.swift.parse",
    "key.length" : 39,
    "key.offset" : 0,
    "key.substructure" : [
      {
        "key.accessibility" : "source.lang.swift.accessibility.internal",
        "key.kind" : "source.lang.swift.decl.function.free",
        "key.length" : 38,
        "key.name" : "abc(argument:)",
        "key.namelength" : 23,
        "key.nameoffset" : 5,
        "key.offset" : 0,
        "key.substructure" : [

        ],
        "key.typename" : "String"
      }
    ]
  }
}
```

How to get `key.parsed_declaration` here? :(

**Comment by johnfairh** [comment]
`$(..)` is a shell feature, it won't work there.  The best thing is for you to study the code I linked, step through in debugger etc, understand how the CLI calls the API you are trying to use.
