### ISSUE TITLE
Update Commandant

### ISSUE THREAD

**Issue by marcelofabri** [jpsim/SourceKitten#623]
Now that SourceKitten requires Swift 5.0 to build, we can update `Carthage/Commandant` to the latest version, which drops the `Result` dependency.

I started doing that, but it broken [some unit tests](https://github.com/jpsim/SourceKitten/blob/3660bae30cdfd81af4e0577d17145bab81a23694/Tests/SourceKittenFrameworkTests/ModuleTests.swift#L26-L37) and it wasn't obvious to me what the fix should be.

**Comment by jpsim** [comment]
We're using the last Commandant version to include an Xcode project, meaning that if we update we can no longer include Commandant as a git submodule without some decent build system changes.

That's also why the unit tests you linked to failed when you upgraded.

**Comment by marcelofabri** [comment]
Ah I didn't notice that! Thanks for the explanation :)

**Comment by ikesyo** [comment]
> We're using the last Commandant version to include an Xcode project, meaning that if we update we can no longer include Commandant as a git submodule without some decent build system changes.

The latest Commandant 0.17.0 still have its Xcode project/workspace, so what does it mean?

**Comment by jpsim** [comment]
> The latest Commandant 0.17.0 still have its Xcode project/workspace, so what does it mean?

🤔 You're absolutely right, I was remembering a PR that was planning on removing it, but clearly that didn't happen. My mistake 😬.

**Comment by jpsim** [comment]
Fixed in #625.
