### ISSUE TITLE
Can this get built to run on Ubuntu and invoked from CLI

### ISSUE THREAD

**Issue by pkasson** [jpsim/SourceKitten#627]
Tried to build a CLI and including kitten in a pod ... built ok, won't run due to what seems like the inability to statically link frameworks (or reference frameworks) from a CLI.

Can this be built to run / be called from a CLI app and run on Ubuntu ?

**Comment by jpsim** [comment]
Sure, you can include SourceKittenFramework in a swift command line executable to run on Ubuntu. [SwiftLint](https://github.com/realm/SwiftLint) does just that.

Can you share more about how you’re building and integrating SourceKittenFramework so I can help?

**Comment by pkasson** [comment]
So I had a simple GUI setup initially to kick off calls to kitten, and converting to run via CLI I just created a new CLI app, with a Podfile with kitten.  All builds ok, but from what I read, Apple has not supported Framework linking with a CLI app.  I can look into SwiftLint to see how they did it.

**Comment by jpsim** [comment]
Are you using CocoaPods on Ubuntu? Is that even supported by them?

**Comment by pkasson** [comment]
Yes .. and yes, I was able to install it on Ubuntu, and the pod install worked.  Swift is supported but not iOS libraries.

**Comment by jpsim** [comment]
Could you please share steps to how I could reproduce this? I've never used CocoaPods on Linux before. I can't find documentation for how to use CocoaPods on Linux. Here's my attempt:

```
$ docker run -it --rm swift:5.1 bash
root@59094128696f:/# apt-get update
root@59094128696f:/# apt install ruby-full sudo
root@59094128696f:/# adduser cocoapods
root@59094128696f:/# gem install cocoapods
root@59094128696f:/# sudo -u cocoapods pod --version
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    
1.8.4
root@59094128696f:/# sudo -u cocoapods pod init
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    
[!] No Xcode project found, please specify one
```

**Comment by pkasson** [comment]
Are you using Linux generic or Ubuntu specifically ?

**Comment by pkasson** [comment]
@jpsim - a question for you ...

When I run structure and syntax, things work fine (kitten on Ubuntu), but when I run doc, while it does dump a Json structure, it also complains (**_meows_**) with:

ubuntu@local: ~/dev/swift/SourceKittenUtil/Sources/SourceKittenUtil$ sourcekitten doc --single-file Logger.swift 
sourcekit: [1:getCursorInfo: 0.0000] failed to create an ASTInvocation: error: no input filessourcekit: [1:getCursorInfo: 0.0006] failed to create an ASTInvocation: error: no input filessourcekit: [1:getCursorInfo: 0.0008] failed to create an ASTInvocation: error: no input filessourcekit: [1:getCursorInfo: 0.0010] failed to create an ASTInvocation: error: no input filessourcekit: [1:getCursorInfo: 0.0013] failed to create an ASTInvocation: error: no input filessourcekit: [1:getCursorInfo: 0.0015] failed to create an ASTInvocation: error: no input filessourcekit: [1:getCursorInfo: 0.0017] failed to create an ASTInvocation: error: no input filessourcekit: [1:getCursorInfo: 0.0020] failed to create an ASTInvocation: error: no input files

**Comment by jpsim** [comment]
> Are you using Linux generic or Ubuntu specifically ?

I'm using the docker image `swift:5.1`, which is Ubuntu 18.04.3 LTS. See https://hub.docker.com/_/swift

Here's what happens when I run `sourcekitten doc --single-file` in Docker:

```
$ docker run -it --rm swift:5.1 bash
$ git clone https://github.com/jpsim/SourceKitten.git
$ cd SourceKitten/
$ echo "struct A { let b: Int }" > file.swift
$ swift run -c release sourcekitten doc --single-file /SourceKitten/file.swift 
sourcekit: [1:getCursorInfo: 0.0000] failed to create an ASTInvocation: error: no input filessourcekit: [1:getCursorInfo: 0.0009] failed to create an ASTInvocation: error: no input files{
  "\/SourceKitten\/file.swift" : {
    "key.diagnostic_stage" : "source.diagnostic.stage.swift.parse",
    "key.length" : 24,
    "key.offset" : 0,
    "key.substructure" : [
      {
        "key.accessibility" : "source.lang.swift.accessibility.internal",
        "key.bodylength" : 12,
        "key.bodyoffset" : 10,
        "key.kind" : "source.lang.swift.decl.struct",
        "key.length" : 23,
        "key.name" : "A",
        "key.namelength" : 1,
        "key.nameoffset" : 7,
        "key.offset" : 0,
        "key.substructure" : [
          {
            "key.accessibility" : "source.lang.swift.accessibility.internal",
            "key.kind" : "source.lang.swift.decl.var.instance",
            "key.length" : 10,
            "key.name" : "b",
            "key.namelength" : 1,
            "key.nameoffset" : 15,
            "key.offset" : 11,
            "key.typename" : "Int"
          }
        ]
      }
    ]
  }
}
```

So I'm also getting the `sourcekit: [1:getCursorInfo: 0.0000] failed to create an ASTInvocation: error: no input files` messages, but other than that log the command works as intended.

I'd suggest filing a bug at https://bugs.swift.org if you'd like to report that log message as a bug.

**Comment by pkasson** [comment]
Well, is it the log message is a bug, OR, that it is not processing the input file at all ?  'no input file' is incorrect, both you and myself received this - so isn't it a SourceKitten bug ?

**Comment by jpsim** [comment]
> Well, is it the log message is a bug, OR, that it is not processing the input file at all ?

That log message isn't coming from SourceKitten, it's coming from SourceKit: https://github.com/apple/swift/blob/7543a89cc483f337cd6b512efc88499d8d7d9773/tools/SourceKit/lib/SwiftLang/SwiftSourceDocInfo.cpp#L1677

It's definitely processing the input file given that SourceKitten outputs the expected JSON based on the file's structure in the example that I shared in my last comment.

> 'no input file' is incorrect, both you and myself received this - so isn't it a SourceKitten bug ?

The question at hand in my opinion is, why is this message logged on Linux but not macOS given the same Swift version and steps followed? There's no OS-specific difference on the SourceKitten side, so the discrepancy is on the SourceKit side. The two likely explanations that I can come up with are:

1. There's a SourceKit bug on Linux; or
2. SourceKit on macOS is too lenient in the face of this error, and doesn't log it

In either case, filing a bug at https://bugs.swift.org as I've suggested would inform the folks who monitor SourceKit bug reports to weigh in on what they think is happening here.

**Comment by pkasson** [comment]
Yes - I saw the output in your last post - but I did not get any.  Agreed on your explanation - like Obj-C, its probably overlooking things that are bad, I will file a bug.  Thanks JP

**Comment by pkasson** [comment]
Opened a bug report on Swift

**Comment by pkasson** [comment]
@jpsim 
Did you ever get it to build on Ubuntu ?  I was getting a build using SPM but after switching to pods, don't see how to get a build.  When doing a swift build it does not work.

**Comment by jpsim** [comment]
I'm very confused. From everything I've seen, CocoaPods requires Xcode to build anything, which is only available on macOS, so I don't see how CocoaPods could be used on Linux to build and run SourceKitten 🤔

**Comment by pkasson** [comment]
yep, must have been something i ate ... mind went off the rails - never mind.
