### ISSUE TITLE
Add support for code formatting in Obj-C header comments

### ISSUE THREAD

**Issue by brycepauken** [jpsim/SourceKitten#631]
This would only require a change in [commentBody()](https://github.com/jpsim/SourceKitten/blob/8c293777af7ed710ecac6f1cae2335cdef2de317/Source/SourceKittenFramework/Clang%2BSourceKitten.swift#L181) in `Clang+SourceKitten.swift` (as best as I can tell!).

Two different scenarios that would be good to support:

    Individual @c Word Highlighting

And:

    Highlighting an entire codeblock:

    @code
    print("Hello world!")
    @endcode

The first should be implementable via regex / wrapping the targeted word in backticks.

The second can be _rougly_ implemented by just replacing `@code` and `@endcode` with triple-backticks, though this would result in different results from Xcode in some scenarios (most of which should be considered error scenarios already / even cause warnings in Xcode, essentially in situations where the keywords are in a different order or count than expected).

**Comment by brycepauken** [comment]
I have a basic implementation of the above strategy locally & will open a PR in a bit, but definitely happy to talk about the change here, including any other ways of tackling this!

**Comment by jpsim** [comment]
Added in #632.
