### ISSUE TITLE
Using SPM, upgrade to kitten 28 breaks build

### ISSUE THREAD

**Issue by pkasson** [jpsim/SourceKitten#641]
Used SPM for 27 and worked ok, tried swift package update, caused build errors - Yaml.h header not found.

Tried to use PM inside Xcode - now getting Framework not found Yams.

Prefer to use SPM from CLI as seemingly more mature, but no joy.

**Comment by jpsim** [comment]
Can you share steps to reproduce the issue? I haven’t had this problem.

**Comment by pkasson** [comment]
Issue was with SPM .. .switched to pods and working as expected
