### ISSUE TITLE
"key.parsed_declaration" serious bug

### ISSUE THREAD

**Issue by catchmeapp** [jpsim/SourceKitten#650]
I've already created the issue #620 for you 6 months ago, but there is no news since then and I still have the problem from #620. I really need `SourceKitten` to create exciting codegen tools, but the key "key.parsed_declaration" doesn't work at all (result dictionary from SourceKitten doesn't have this key). Please tell me what to do, I'm desperate.

**Comment by catchmeapp** [comment]
@johnfairh maybe you can help me, I saw that you have fixed something with "key.parsed_declaration"

**Comment by jpsim** [comment]
John actively discussed with @incetro in the issue you linked, and that user closed the issue a few days ago.

Can you please share a complete report of the exact commands you've run, what you were expecting to happen, and what actually happened instead?

Also, assuming you're running the `sourcekitten doc` command, did you try any of the examples listed here? https://github.com/jpsim/SourceKitten#doc

If not, can you please try? If you did and it didn't work, can you please share how it failed?

Thank you.

**Comment by catchmeapp** [comment]
Hey. This answer helped me to figure out a solution for my problem, I will also close the issue, thanks a lot.
