### ISSUE TITLE
EXC_BAD_ACCESS with 0.28.0 onwards when using inside XCTest bundle

### ISSUE THREAD

**Issue by ianbytchek** [jpsim/SourceKitten#653]
Hello friends! Trying to update [Slang](https://github.com/Swifteroid/Slang) to run with the latest build and stumbling across a very bizarre crash inside the test suite when getting file lines:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/1086845/82739080-ac222300-9d34-11ea-9b0d-e01f9c9db4e2.png">

This doesn't happen with 0.26.0 and 0.27.0, only in 0.28.0 and above, where [StringView](Source/SourceKittenFramework/StringView.swift) was introduced, I'm just guessing that this has something to do with it. I know that this is most likely a glitch within `DispatchQueue` inside XCTest bundle, I've seen some weirdness in the past. For example, this almost doesn't happen (very-very rarely) when running a single test, but occurs solidly when running all tests. At the same time, 0.27 doesn't look that much different to 0.28, however, the crash doesn't happen there. It doesn't occur at the same place, but always when calling `_contentsQueue.sync` inside `_stringViewQueue.sync`. This isn't a deadlock, but looks very much like some race condition…

I'm wondering if you've dealt with anything like that before? Any advice?

Also, is there any reason why SourceKitten uses queues for atomic ops and not locks? Is that a Linux-related issue or is there a different reason?

**Comment by ianbytchek** [comment]
Yep, this definitely started happening after #629 somewhere along these commits. 

<img width="614" alt="image" src="https://user-images.githubusercontent.com/1086845/82739718-d2968d00-9d39-11ea-9e52-d00ed3413eb5.png">

2ea5693431985b7978efaabf2f9a3fa8f8f5b75c fails me, 66248f52a1d9a0940a9b03ac85769b3d18eefdbe doesn't.

**Comment by ianbytchek** [comment]
@PaulTaykalo @jpsim politely pinging you in guys.

**Comment by PaulTaykalo** [comment]
Looks like a race. I won't have an access to the computer until Monday. Can you please ping me politely again? :)

**Comment by PaulTaykalo** [comment]
@ianbytchek how can I run Slang? It gives me errors on depdendencies.

**Comment by PaulTaykalo** [comment]
![image](https://user-images.githubusercontent.com/119268/82760709-1e126f00-9dfe-11ea-9d06-358ddad50925.png)

**Comment by PaulTaykalo** [comment]
![image](https://user-images.githubusercontent.com/119268/82761389-d9d59d80-9e02-11ea-867c-0891c5ea4472.png)
20 from 20. 
What Xcode are you using?

**Comment by ianbytchek** [comment]
Install Git submodules with `git submodule update --init --recursive`. Need to remove them or update README, sorry. Bump SourceKit version in Carthage and run the tests.

**Comment by ianbytchek** [comment]
Using the latest 11.5, updated yesterday from the previous in hopes that it would solve this.

**Comment by PaulTaykalo** [comment]
🤔 Same here.

**Comment by ianbytchek** [comment]
Did you update SourceKit in Cartfile? 🤔

**Comment by PaulTaykalo** [comment]
yep.

**Comment by PaulTaykalo** [comment]
![image](https://user-images.githubusercontent.com/119268/82761502-a1828f00-9e03-11ea-8105-165c0cfb2de4.png)

**Comment by PaulTaykalo** [comment]
@ianbytchek can you check what's going on in other threads when this crash is happening?

**Comment by ianbytchek** [comment]
Wow. Okay… Can you also try cleaning the build folder? Threads look clean, nothing else is locking the queue, hence why this looks super-weird… Just cleaned everything, updated to 0.28 with build from sources and here we go:

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/1086845/82761607-b2c39f80-9df3-11ea-8d15-c1a9f5ec1529.png">

**Comment by PaulTaykalo** [comment]
@ianbytchek 
- Please give me your carthge CLI call
- Can you set Zombies Enabled and try to reproduce
- Also, Thread / Address sanitizer can probably should help.
- Is it the first test when it fails? Any additional settings on the Test Scheme? (Run in parallel/ etc)?

**Comment by ianbytchek** [comment]
Was looking into [EXC_I386_GPFLT bug](https://bugs.swift.org/browse/SR-6003) and tried enabling [Address Sanitizer + Zombie Objects](https://user-images.githubusercontent.com/1086845/82762007-4c8c4c00-9df6-11ea-93b2-764ed77b457d.png) scheme options, and everything worked! Disabling Address Sanitizer would result in the same crash as before (with With Zombie Objects only). [All Memory Management group selected](https://user-images.githubusercontent.com/1086845/82762063-bc023b80-9df6-11ea-8233-c2424ecb5d48.png) gives an even more weird [crash](https://user-images.githubusercontent.com/1086845/82762057-b147a680-9df6-11ea-90e7-898226f327f9.png).

Here's Carthage update output:

```sh
$ carthage update --platform macOS
*** Fetching Regex
*** Fetching Quick
*** Fetching SourceKitten
*** Fetching Nimble
*** Fetching Yams
*** Fetching SWXMLHash
*** Checking out Quick at "v2.2.0"
*** Checking out Nimble at "v8.0.9"
*** Checking out SourceKitten at "0.28.0"
*** Checking out Regex at "2.1.1"
*** Checking out Yams at "2.0.0"
*** Checking out SWXMLHash at "5.0.1"
*** xcodebuild output can be found in /var/folders/9m/j19r54j52cggdx6l9d6xdbjc0000gn/T/carthage-xcodebuild.Z1F7iQ.log
*** Downloading SourceKitten.framework binary at "0.28.0: Ball of Twine"
***  Skipped installing SourceKitten.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)."

    Falling back to building from the source
*** Building scheme "Nimble-macOS" in Nimble.xcodeproj
*** Building scheme "Quick-macOS" in Quick.xcworkspace
*** Building scheme "Regex-OSX" in Regex.xcodeproj
*** Building scheme "SWXMLHash OSX" in SWXMLHash.xcworkspace
*** Building scheme "Yams" in Yams.xcodeproj
*** Building scheme "SourceKittenFramework" in SourceKitten.xcworkspace
```

> Is it the first test when it fails? Any additional settings on the Test Scheme? (Run in parallel/ etc)?

I believe everything is standard, see [here](https://user-images.githubusercontent.com/1086845/82762142-42b71880-9df7-11ea-8a41-35e75fc764b1.png). This was my initial idea as I've done something similar in the past, but didn't find any references + parallel run is disabled anyway. Are there any other tweaks to try? 

The crash happens before it gets to any tests, like [here](https://github.com/Swifteroid/Slang/blob/8e5be3b351914843d6272fd676fcd9a8266a1a95/source/Slang/Test/Source/Query/Test.Source.Query.Fragment.swift#L15), I tried moving everything inside "it(…)" bodies, but it would produce the same result.

**Comment by PaulTaykalo** [comment]
What Carthage version do you have?

**Comment by ianbytchek** [comment]
```sh
$ carthage version 
0.34.0
```

**Comment by PaulTaykalo** [comment]
Can it be that you have some custom ToolChains installed? 
![image](https://user-images.githubusercontent.com/119268/82763123-f7f4cb00-9e0d-11ea-8f76-35afe5f5404c.png)

**Comment by PaulTaykalo** [comment]
Ok. What hardware do you have? and what OS (I believe Catalina, but who knows)

**Comment by PaulTaykalo** [comment]
Okay. Just in case if nothing will work, could you, please, compress Sourcekitten.framework, compiled by he Carthage, and place it here, or somewhere I can download. May be it something on the binary level?
I'm out of options atm.

**Comment by ianbytchek** [comment]
No, literally everything everything as standard as it gets. Xcode Version 11.5 (11E608c) with no custom toolchains, that menu isn't even there.

<img width="698" src="https://user-images.githubusercontent.com/1086845/82763276-60d44700-9dfe-11ea-89e2-221088a5f05e.png">

Yes, I've tried rebooting, clearing all system caches and derived data, etc. Here's the Carthage-built [SourceKittenFramework.zip](https://github.com/jpsim/SourceKitten/files/4674287/SourceKittenFramework.zip), doubt it's the problem.

P.S. I'm shuffling some code around and was able to get the linker failing while linking Slang's `File` with the test bundle after changing the `init` signature (SourceKitten also has `File`). The above [bug reference](https://bugs.swift.org/browse/SR-6003) mentioned something about two same-named files causing this crash. Just started looking into this, but so far this whole issue smells like more of a system-level glitch. Will keep you posted.

**Comment by ianbytchek** [comment]
Okay. I have figured it out: I am cursed.

**Comment by ianbytchek** [comment]
`carthage build --no-skip-current` + `LD_RUNPATH_SEARCH_PATHS = $(inherited) $(FRAMEWORK_SEARCH_PATHS)` = 💥

Lucky you asked for the zipped copy, I noticed the `Slang.framework` hanging in Carthage build folder and after more linker weirdness it stroke me that it's linking the old framework… 🤦‍♂️

Thanks for looking into this!

**Comment by PaulTaykalo** [comment]
Nice!
