### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by Fedos** [jpsim/SourceKitten#665]
Outdated Yams dependency (2.0) in latest release is conflicting with other libraries like SwiftGen

**Comment by hungrxyz** [comment]
Yes please, currently stuck on using SwiftLint and SwiftGen together because of outdated Yams versions.

**Comment by jpsim** [comment]
SourceKitten 0.30.0 was just released along with Yams 4.0.0: https://github.com/jpsim/SourceKitten/releases/tag/0.30.0
