### ISSUE TITLE
'sortedKeys' is only available in iOS 11.0 or newer

### ISSUE THREAD

**Issue by chepiok** [jpsim/SourceKitten#687]
in JSONOutput.swift, .sortedKey is used but protected only by a if #available(macOS 10.13, *). Should be 11.* according to the compiler.

**Comment by jpsim** [comment]
If you're getting this error, it's because you're trying to compile SwiftLint for iOS, which it doesn't support. Only macOS & Linux are supported.

Can you please post the detailed steps you're taking to build/run/integrate SwiftLint so I can help identify the issue?

**Comment by chepiok** [comment]
In fact I was using SourceKitten throught dependency coming from realm/SwiftLint. Which was on iOS.

**Comment by jpsim** [comment]
Yeah you won't be able to build SourceKitten or anything that depends on it (e.g. SwiftLint, Sourcery, etc) targeting iOS. You can only build for macOS and iOS.
