### ISSUE TITLE
Kitten won't build with Big Sur and Xcode (Version 12.4 (12D4e))

### ISSUE THREAD

**Issue by pkasson** [jpsim/SourceKitten#693]
From command line (as others have noted), have never had issue building kitten or my project using kitten.

Switching to Big Sur and XC 12.4, kitten now shows that it cant find type 'StringView'  or 'Line' in File.swift:

`
    /// File contents.
    public var contents: String {
        get {
            _contentsQueue.sync {
                if _contents == nil {
                    _contents = try! String(contentsOfFile: path!, encoding: .utf8)
                }
            }
            return _contents!
        }
        set {
            _contentsQueue.sync {
                _contents = newValue
                _stringViewQueue.sync {
                    _stringView = nil
                }
            }
        }
    }

    public var stringView: StringView {
        _stringViewQueue.sync {
            if _stringView == nil {
                _stringView = StringView(contents)
            }
        }
        return _stringView!
    }

    public var lines: [Line] {
        return stringView.lines
    }

    private var _contents: String?
    private var _lines: [Line]?
    private var _stringView: StringView?
    private let _contentsQueue = DispatchQueue(label: "com.sourcekitten.sourcekitten.file.contents")
    private let _stringViewQueue = DispatchQueue(label: "com.sourcekitten.sourcekitten.file.stringView")
`

Error is:  Type of expression is ambiguous without more context (that is for _stringViewQueue.sync) where as all other StringView errors show:

Cannot find type 'StringView' in scope

For Line - same error - cant find in scope.

Build is using:

     .package(url: "https://github.com/jpsim/SourceKitten.git", .exact("0.28.0")),
     .package(url: "https://github.com/jpsim/Yams.git", from: "2.0.0"),

**Comment by jpsim** [comment]
I haven’t seen this in my integrations with SourceKitten. Can you please share complete steps to reproduce this problem so I can look into it?

**Comment by pkasson** [comment]
Nothing changed from a build perspective, except:

Running on Big Sure
Xcode version is latest (12.4)

**Comment by jpsim** [comment]
Closing as I can’t do much without steps to reproduce.
