### ISSUE TITLE
Why doesn't the commentBody method on String support simple multiline comment types?

### ISSUE THREAD

**Issue by revolter** [jpsim/SourceKitten#695]
Specifically, this line:

https://github.com/jpsim/SourceKitten/blob/357fd69eab8469688b6e4d998226ca15810bed1e/Source/SourceKittenFramework/String%2BSourceKitten.swift#L59

should be

```swift
("^\\s*\\/\\*(?:\\*)?\\s*(.*?)\\*\\/", [.anchorsMatchLines, .dotMatchesLineSeparators]), // multi: ^\s*\/\*(?:\*)?\s*(.*?)\*\/
```

instead, so it could match `/* comment */` too, and not only `/** comment */`.

**Comment by johnfairh** [comment]
The routine is used to extract documentation comments for docs generation, so it would be wrong to match `/* ` comments.  I agree with you this is not at all clear from its own doc comment & name.

**Comment by revolter** [comment]
I see. So there isn't a different method that returns the contents of a comment line or block?

**Comment by johnfairh** [comment]
No, I don't think so.

**Comment by revolter** [comment]
Ok, thanks for the help!
