### ISSUE TITLE
If the code has unicode characters , all offsets are offset by codepoint amounts . 

### ISSUE THREAD

**Issue by diiiv9** [jpsim/SourceKitten#701]
In the code below because of the copyright symbol all offsets in `Structure` are offset by 1 . If I add another © then they increase by 2 . 

`
//
//  TestProject.swift
//  PseudoProject
//
//  Created by That on 15/06/21.
//  Copyright © 2021 C. All rights reserved.
//

import UIKit

public class TestProject : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawCanvas1(frame: CGRect = CGRect(x: 26, y: 14, width: 176, height: 90)) {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: frame.minX + 30.5, y: frame.minY + 74.5))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 134.5, y: frame.minY + 0.5))
        UIColor.black.setStroke()
        bezierPath.lineWidth = 6
        bezierPath.lineCapStyle = .round
        bezierPath.stroke()
    }

}
`

**Comment by diiiv9** [comment]
[sksample.txt](https://github.com/jpsim/SourceKitten/files/6654300/sksample.txt)

**Comment by johnfairh** [comment]
SourceKit offsets are bytes; that copyright symbol is two bytes in UTF-8. See eg. #608.

**Comment by diiiv9** [comment]
Ok ! Thanks . NSString should work fine right then ? 
Could you also please help me out with the other issue as to why some expression calls are missing in the structure ( like the `bezierPath.lineCapStyle = .round` in this example ) . 

Thanks again , SourceKit has been really helpful .

**Comment by johnfairh** [comment]
I'm not sure about `NSString` - maybe see sourcekitten's `StringView` type and its byte-related methods.

I didn't comment on your other issue because I'm not familiar with how structure is supposed to work inside methods.

**Comment by jpsim** [comment]
Let us know if you have further questions!
