### ISSUE TITLE
SourceKitten not reporting function substructure when only instance variable is changed

### ISSUE THREAD

**Issue by KaneCheshire** [jpsim/SourceKitten#704]
We have an [issue with the latest version of SwiftLint ](https://github.com/realm/SwiftLint/issues/3647)and it seems as though it is because of a bug with SourceKitten itself. This has only manifested since updating to the latest version of SwiftLint, which is also using the latest version of SourceKitten.

### TL;DR:

When provided with the following code:

```swift
class TotoTests: XCTestCase {
    var foo: String = ""

    override func setUp() {
        foo = "bar"
    }
}
```

SourceKitten does not report any substructure for the setUp() function, despite containing valid code in there.

### More info

I've put together a test case which shows the issue:

```swift
func testBug() throws {
        let contents = "class TotoTests: XCTestCase {\n    var foo: String = \"\"\n    override func setUp() {\n        foo = \"bar\"\n    }\n}"

        let structure = try Structure(file: .init(contents: contents))
        let substructureArray = try XCTUnwrap(structure.dictionary["key.substructure"] as? [SourceKitRepresentable])
        let substructureDictionary = try XCTUnwrap(substructureArray.first as? [String : SourceKitRepresentable])

        let typeName = try XCTUnwrap(substructureDictionary["key.name"] as? String)
        XCTAssertEqual(typeName, "TotoTests")

        let typeSubstructureArray = try XCTUnwrap(substructureDictionary["key.substructure"] as? [SourceKitRepresentable])
        XCTAssertEqual(typeSubstructureArray.count, 2) // Only has one property and one function

        let propertySubstructureDictionary = try XCTUnwrap(typeSubstructureArray[0] as? [String: SourceKitRepresentable])
        let propertyName = try XCTUnwrap(propertySubstructureDictionary["key.name"] as? String)
        XCTAssertEqual(propertyName, "foo")

        let functionSubstructureDictionary = try XCTUnwrap(typeSubstructureArray[1] as? [String: SourceKitRepresentable])
        let functionName = try XCTUnwrap(functionSubstructureDictionary["key.name"] as? String)
        XCTAssertEqual(functionName, "setUp()")

        let functionContentsArray = try XCTUnwrap(functionSubstructureDictionary["key.substructure"] as? [SourceKitRepresentable])
        XCTAssertEqual(functionContentsArray.count, 1)
    }
```

Just to validate, if you change the `contents` to this: 

```swift
let contents = "class TotoTests: XCTestCase {\n    var foo: String = \"\"\n    override func setUp() {\n        let foo = \"bar\"\n    }\n}"
```

Then the test passes fine. It's only an issue when setting an instance variable, rather than a local variable:

<img width="1789" alt="Screenshot 2021-09-16 at 11 44 54" src="https://user-images.githubusercontent.com/10811515/133599879-ee20d415-e61b-44b5-9e40-f56b115f4f5e.png">

<img width="1778" alt="Screenshot 2021-09-16 at 11 56 07" src="https://user-images.githubusercontent.com/10811515/133600192-508fbc6c-9307-449e-b471-62590ba8d04b.png">

Additionally a [similar issue was raised on the SwiftLint repo](https://github.com/realm/SwiftLint/issues/3691) which I believe to be because of the same issue in SourceKitten.

I hope this helps debug, I don't know much more about SourceKitten but I can try and take a look at fixing too, but raising here because likely the code owner(s) will be able to fix it faster :)

**Comment by KaneCheshire** [comment]
Oh I should also say, this is running the tests in Xcode 12.5.1, I haven't tried any other versions or toolchains.

**Comment by johnfairh** [comment]
The `Structure` API in SourceKitten makes a single query to SourceKit, `source.request.editor.open`, and returns the doc structure results without modification.  You could check on the Swift nightly toolchain: if it's still a problem then the question -- something like "Assignment expressions missing from doc structure' belongs with [the Swift project](https://bugs.swift.org/).

**Comment by KaneCheshire** [comment]
Okay thanks for getting back to me, I notice it does pick up if you do `foo = String()` so guess it's a Swift issue then

**Comment by johnfairh** [comment]
Right -- just for interest, notice there you get just a `source.lang.swift.expr.call` inside the substructure which is the `String()` part -- the assignment part itself is not mentioned.
