### ISSUE TITLE
Objective C / C++ Union Support

### ISSUE THREAD

**Issue by bosborn** [jpsim/SourceKitten#705]
Any chance of supporting `union` similar to `struct` in [ObjCDeclarationKind.swift](https://github.com/jpsim/SourceKitten/blob/master/Source/SourceKittenFramework/ObjCDeclarationKind.swift)?

Running jazzy version 0.14.0 with a C++ dependency already built, receiving the following error:
SourceKittenFramework/ObjCDeclarationKind.swift:81: Fatal error: Unsupported CXCursorKind: UnionDecl

Manually changing `union` in the offending file to `struct` allows documentation to generate.

Example:
`typedef union { double  a; int  b; char *c; } VALUE;`
to
`typedef struct { double  a; int  b; char *c; } VALUE;`

**Comment by johnfairh** [comment]
There's a good chance all this needs is adding `CXCursor_UnionDecl` in that file and a quick testcase in `ClangTranslationUnitTests` -- this does look to be a missing ObjC feature though can't be that common in practice as I don't remember hearing a request for it before.

**Comment by bosborn** [comment]
Took a shot at it in #706.  Not too familiar with the testing framework, so based it on the results from using struct.
