### ISSUE TITLE
Is there any way to fetch USR via SwiftDocs for Swift files?

### ISSUE THREAD

**Issue by hulizhen** [jpsim/SourceKitten#720]
As per the title, I'm trying to figure out how to get the USR and docs info with the `SwiftDocs` class in one time, instead of requesting `index` and `editorOpen` separately, and then merging them together.

Any help would be appreciated :)

**Comment by johnfairh** [comment]
SourceKitten's `SwiftDocs` information returns USR etc. info, by issuing `editorOpen` then multiple `cursorInfo`s.  See the test output eg. [here](https://github.com/jpsim/SourceKitten/blob/9c464c0ba95b6181932a3f7f4e2c8510b05145a9/Tests/SourceKittenFrameworkTests/Fixtures/Bicycle%40swift-5.5.json) for what you should be getting.

If this isn't what you want, then you should probably ask on the Swift forums about help with using SourceKit.  Be very clear what information you want; and it might be worth saying why you must have a single request -- it could be you have some wrong assumptions.

**Comment by hulizhen** [comment]
@johnfairh Amazing! By comparing the parameters used in `SwiftDocsTests`, I found that passing a relative path of Swift file is reason why it didn’t generate the USR info. After passing an absolute path, I can now get a lot more infos from the result.

Thanks a million, you really just saved my day :)
