### ISSUE TITLE
Possibility of running multiple sourcekitten services in parallel

### ISSUE THREAD

**Issue by acecilia** [jpsim/SourceKitten#721]
👋

#### Context

My machine is an 2019 macbook pro, 8 core CPU. This allows for 16 threads. Thus, when I run `yes > /dev/null &` 8 times, I am getting a 50% CPU utilization, and when running it 16 times I get 100% utilization:

<img width="300" alt="Screenshot 2021-11-27 at 04 18 26" src="https://user-images.githubusercontent.com/7938671/143667760-8913dbc7-3922-453e-94f7-5fe1f4249201.png">

#### The problem

I am running the `analyze` command from swiftlint. When doing that, I observe the following:
* The CPU utilization usually stays around 50%, even though swiftlint is using [concurrentPerform](https://github.com/realm/SwiftLint/blob/86b6392aa22bb4b91a8f033d4dd11c8e4ab87b8f/Source/swiftlint/Extensions/Array%2BSwiftLint.swift#L11) when analyzing and is correctly starting 16 threads (I checked):

    <img width="300" alt="Screenshot 2021-11-27 at 04 14 31" src="https://user-images.githubusercontent.com/7938671/143667837-bd469029-8a80-421a-8cab-03834de6fe2d.png">

* There is one unique `SourceKitService` that takes care of executing all requests
* I did manually update the source code of swiftlint to start 32 threads, but the CPU utilisation was the same

Seeing above, I am wondering if maybe the single instance of `SourceKitService` is wrongly limiting the amount of threads it uses to process the requests, not taking full advantage of the available computing power. Thus the question:
* Is there any way to indicate `SourceKitService` how many threads to use when handling incoming requests?
* If not, would it make sense to use multiple `SourceKitService`? 
* Does this library support running multiple `SourceKitService` instances? Looking at [this](https://github.com/jpsim/SourceKitten/blob/master/Source/SourceKittenFramework/Request.swift#L99) line, seems like not currently possible

Thanks! 🙌

**Comment by johnfairh** [comment]
You may have misread this, it's `SourceKitService` (no kitten) which is part of the Swift compiler.  I think you'd do better asking the SwiftLint team what their expectations are, and then if it looks to you like they are submitting enough jobs in parallel to SourceKitten, follow up with the Swift SourceKit team.

**Comment by acecilia** [comment]
@johnfairh Yes you are right, I miss wrote it. Fixed, thanks! 🙌 

I added the question in this repository because the issue is regarding the possibility of running multiple instances of `SourceKitService` in parallel:

> Does this library support running multiple `SourceKitService` instances? Looking at this line, seems like not currently possible

**Comment by johnfairh** [comment]
Right, but `SourceKitService` is still part of the Swift compiler.  `SourceKitten` does not "start" `SourceKitService`.  That's why the Swift SourceKit team are the people to ask about this.

**Comment by acecilia** [comment]
Got it, thanks 🙌

**Comment by jpsim** [comment]
@johnfairh's right, if you want SourceKit itself to behave differently, then you'd need to discuss that with the team within Swift that works on that. The [Source Tooling](https://forums.swift.org/c/development/tooling/39) category of the Swift Forums is a good place to start a discussion on this.

**Comment by acecilia** [comment]
Thanks! Already opened a [topic](https://forums.swift.org/t/sourcekitservice-only-using-50-of-cpu/53747), lets see
