### ISSUE TITLE
SourceKittenFramework is built without headers (?)

### ISSUE THREAD

**Issue by tjarratt** [jpsim/SourceKitten#73]
Hey, I'd like to say first that I really appreciate this framework. It's clear that a lot of work went into it and I'm really excited to use it to build better tooling for swift.

The problem that I'm having seems ... impossible. I'm building the SourceKitten framework and expecting to be able to bring that into an OS X project and link against it, but I'm finding that the SourceKitten.h umbrella header doesn't exist.

```shell
make installables
# build output here #

± ls -lsh /usr/local/Frameworks/SourceKittenFramework.framework
total 16
8 lrwxr-xr-x  1 root  wheel    26B Oct 11 12:16 Resources -> Versions/Current/Resources
8 lrwxr-xr-x  1 root  wheel    38B Oct 11 12:16 SourceKittenFramework -> Versions/Current/SourceKittenFramework
0 drwxr-xr-x  4 root  wheel   136B Oct 11 12:16 Versions
```

I haven't used frameworks that mix Obj-C with Swift before, but my expectation is that there should still be an umbrella header here in the `Headers` directory.

**Comment by segiddins** [comment]
SourceKittenFramework isn't written in such a way that being able to import it from ObjC would be very useful -- it's almost entirely pure Swift.

**Comment by tjarratt** [comment]
Okay, so your suggestion is to only consume the framework from Swift? That's entirely reasonable, but not well documented.

Is it safe to assume that [the open and incomplete pull request to add Obj-C support](https://github.com/jpsim/SourceKitten/pull/57) might improve this?

**Comment by segiddins** [comment]
No, the ObjC pr just will allow SourceKitten to interface with clang, it will continue to do so entirely through swift.

**Comment by jpsim** [comment]
> Okay, so your suggestion is to only consume the framework from Swift? That's entirely reasonable, but not well documented.

Sorry that was unclear. I've just pushed a section about SourceKittenFramework to the README which will hopefully clarify this for others in the future.

**Comment by tjarratt** [comment]
Thank you so much for the swift[1] responses JP and Samuel! I really appreciate the help.

1) no pun intended
