### ISSUE TITLE
 Incredibly weird "illegal hardware instruction" error

### ISSUE THREAD

**Issue by monession** [jpsim/SourceKitten#735]
Hey. I caught weird error with "illegal hardware instruction"

I have `BookPlainObject.swift` file with the given code:
```swift
enum Test {
    case something
}
```

And call `sourcekitten doc --single-file BookPlainObject.swift -- -j4 -sdk $(xcrun --show-sdk-path -sdk macosx) $(pwd)/BookPlainObject.swift > sk.sh.txt` in terminal.

Then I got this error:
`[1]    20090 illegal hardware instruction  sourcekitten doc --single-file BookPlainObject.swift -- -j4 -sdk   > sk.sh.tx`

BUT if I replace `BookPlainObject.swift` file content:
```swift
enum Test {
    static let something = 0
}
```
everything works fine.

Also it works with classes, structures, etc. 

But totaly not working with enum + case syntax

P.s. I'm sure there is right encoding in my files (I've checked it)

**Comment by johnfairh** [comment]
Can you double-check the sourcekitten version?

From your description it sounds like #727 which was included in version 0.32.0.

If you're definitely running latest code then please let us know the Swift & OS versions you're using.
