### ISSUE TITLE
dyld: Library not loaded: @rpath/libclang.dylib

### ISSUE THREAD

**Issue by paulyoung** [jpsim/SourceKitten#77]
I'm getting this message when trying to run any `sourcekitten` command.

```
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/SourceKittenFramework
  Reason: image not found
Trace/BPT trap: 5
```

I installed 0.5.1 via the package on the release page. I'm on El Capitan, version 10.11.1 (15B42)

It's been a while since I did anything with SourceKitten but seem to remember encountering this before with an older version.

**Comment by paulyoung** [comment]
My command line tools are pointed to Xcode 7.1 (7B91b) in case that's of any interest.

**Comment by jpsim** [comment]
You'll get this error if you don't have an Xcode installed or symlinked exactly under `/Applications/Xcode.app`.

**Comment by paulyoung** [comment]
I currently have Xcode 7.1 as `/Applications/Xcode.app`. Is there a specific version that is known to work?

**Comment by jpsim** [comment]
That should work. I don't know why it isn't.

**Comment by terhechte** [comment]
I had the same problem when I installed sourcekitten via the .pkg. After that I did a git clone / make install and that worked.

**Comment by paulyoung** [comment]
I installed `swiftlint` via Homebrew and get a similar message:

```
$ swiftlint lint
dyld: Library not loaded: @rpath/libswiftSecurity.dylib
  Referenced from: /Library/Frameworks/SourceKittenFramework.framework/SourceKittenFramework
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by dmitriyl** [comment]
Looks like I have same issue
dyld: Library not loaded: @rpath/Yams.framework/Versions/A/Yams
  Referenced from: /Users/user/Library/Developer/Xcode/DerivedData/Analyzer-baeifizhbjjykhgwfvcnzpqspiku/Build/Products/Debug/Analyzer
  Reason: image not found
