### ISSUE TITLE
Crash when running sourcekitten

### ISSUE THREAD

**Issue by nrbrook** [jpsim/SourceKitten#770]
The following Objective-C code causes sourcekitten to crash:

```
/**
 Description
 @param param1 Parameter 1
 @param param2 Parameter 2
 */
@property(nonatomic, strong, nullable) void (^someBlock)(UIView *_Nullable param1, UIView *_Nullable param2);
```

**Comment by johnfairh** [comment]
`libclang` is crashing when asked to give the XML version of the `CXComment_FullComment` for that comment:
<img width="735" alt="Screenshot 2023-05-16 at 08 58 17" src="https://github.com/jpsim/SourceKitten/assets/26768470/d44dde84-eac4-4d3e-a8ed-fde6bbe87fc4">

Looks like it expects `@param` is only for documenting method parameters not block property parameters.  If I write `@param fred stuff` then it's fine -- so I guess it is getting some unfortunate partial match.

**Comment by jpsim** [comment]
Thanks for reporting this @nrbrook and @johnfairh for looking into it. @nrbrook have you filed feedback with Apple about the libclang crash? I'll close this since this is happening outside of SourceKitten.

**Comment by nrbrook** [comment]
I haven’t reported it. @johnfairh perhaps it would be better for you to report as you have been able to diagnose further?
