### ISSUE TITLE
Error: No such module 'SWXMLHash'

### ISSUE THREAD

**Issue by fresh-Blood** [jpsim/SourceKitten#771]
After adding via spm, when try to compile, in Clang+SourceKitten I see that error. Help please: 

<img width="1637" alt="Снимок экрана 2023-06-01 в 08 47 39" src="https://github.com/jpsim/SourceKitten/assets/88098218/439fdaff-e0af-4e41-9786-5c4a390802e1">

**Comment by jpsim** [comment]
Can you share complete steps to reproduce the issue? SwiftLint pulls in SourceKittenFramework as a SwiftPM dependency and I haven't encountered this problem there.

**Comment by pallavtrivedi03** [comment]
@fresh-Blood  Did you get the solution. I'm facing the same error. 

@jpsim I installed the SourceKitten from SPM. I can see that SWXMLHash is also installed, but for some reason, SourceKitten cannot find it - "No such module SWXMLHash".

![Screenshot 2023-09-25 at 11 16 27 PM](https://github.com/jpsim/SourceKitten/assets/6988625/213c0e42-a051-421a-be49-98b134753823)

**Comment by fresh-Blood** [comment]
nope (
