### ISSUE TITLE
Complete command use

### ISSUE THREAD

**Issue by mttcrsp** [jpsim/SourceKitten#86]
I'm having troubles using the `complete` command:
- every time I try to use it with the `--file` argument I get a `Failed to read file at ...` error, while the `syntax` command works just fine on the same file;
- completion results do not always show up, as an example: `sourcekitten complete --text "[1].m" --offset 4` works just fine and shows all of the available options, `sourcekitten complete --text "[1].m" --offset 5` returns an empty array while it should return an option for the map function.

Loving the project.

(SourceKitten 0.5.0 installed via Homebrew, Xcode 7.1)

![severalregularfoxterrier](https://cloud.githubusercontent.com/assets/7688838/10982457/956696ea-840d-11e5-9681-ed44323b5214.gif)

**Comment by jpsim** [comment]
The `complete` command expects absolute paths to the file. that's less than ideal and I should improve that so it supports relative paths.

**Comment by jpsim** [comment]
> completion results do not always show up, as an example: sourcekitten complete --text "[1].m" --offset 4 works just fine and shows all of the available options, sourcekitten complete --text "[1].m" --offset 5 returns an empty array while it should return an option for the map function.

This is actually a limitation in how SourceKit generates completion requests, so there's not much I can do for you there.

**Comment by mttcrsp** [comment]
Ok, thanks for the immediate feedback! :+1:

**Comment by jpsim** [comment]
SourceKitten handles relative paths much better now thanks to #101.
