### ISSUE TITLE
Making SwiftDocKey and its methods public

### ISSUE THREAD

**Issue by paulyoung** [jpsim/SourceKitten#87]
I think this would be useful. Are there any reasons not to do this, or an alternative that doesn't require it?

**Comment by jpsim** [comment]
The reason why these aren't public is that none of the current consumers of SourceKitten (jazzy & SwiftLint) need access to them.

If I knew what your interest and goals with SourceKitten were, I could better decide if the best course is to just make these public, or to expose the information from them some other way.

**Comment by paulyoung** [comment]
For example:

```
let docs = SwiftDocs(file: file, arguments: arguments)
let dict = toAnyObject(docs.docsDictionary)
```

In this case I'd then need to resort to `dict["key.substructure"]` instead of `dict[SwiftDocKey.Substructure.rawValue]` or even better, `SwiftDocKey.getSubstructure(dict)`.

**Comment by paulyoung** [comment]
To provide some more context, I'm currently interested in the following:

- `key.parsed_declaration`
- `key.name`
- `key.typename`
- `key.accessibility`

I know some of these _don't_ have methods on `SwiftDocKey` so would be happy to contribute those _or_ just create a local `extension`, provided that `get` was also made `public`.

**Comment by jpsim** [comment]
I wonder if serializing the `XPCDictionary`s `SwiftDoc` structs would be preferable to continuing with this largely untyped approach?

**Comment by paulyoung** [comment]
I think you're proposing something more like:

```swift
public enum Accessibility: String {
    case Internal = "source.lang.swift.accessibility.internal"
    case Private = "source.lang.swift.accessibility.private"
    case Public = "source.lang.swift.accessibility.public"
}

public struct Substructure {
    let accessibility: Accessibility
    let name: String
    let parsedDeclaration: String
    let typeName: String
    ...
}
```

and so on.

**Comment by jpsim** [comment]
Yup.

**Comment by paulyoung** [comment]
This is the direction I was heading in. Would much prefer that.

**Comment by paulyoung** [comment]
I'm planning on doing something around this, just been busy :bee:

**Comment by paulyoung** [comment]
I worked on this a bit last night by simply taking the JSON fixtures and creating new structs based on their content.

This morning I realize that most of this is already represented but not all of it in the same 1-1 mapping. In short, I think the same thing could be achieved adding some properties to the existing `Documentation` and `SourceDeclaration` types instead.

@jpsim does that sound OK to you?

**Comment by paulyoung** [comment]
For what it's worth, here's my naive representation (similar to `SourceDeclaration`):

```
public struct ParsedScope {
    let start: Int
    let end: Int
}

public struct Substructure {
    let kind: SwiftDeclarationKind
    let offset: Int
    let parsedDeclaration: String
    let nameLength: Int
    let bodyOffset: Int
    let bodyLength: Int
    let length: Int
    let doc: Documentation
    let name: String
    let typeName: String
    let parsedScope: ParsedScope
    let usr: String
    let nameOffset: Int
    let annotatedDeclaration: String?
    let accessability: Accessibility?
    let substructure: [Substructure]
    let filepath: String
}
```

I imagine we may not want/need all of these based on some existing code I've seen.

Here's a diff representing the (again, naive) changes I made to `Documentation`:
```
public struct Documentation {
+    let comment: String
+    let line: Int
+    let column: Int
+    let type: String
+    let file: String
+    let fullAsXml: XMLElement
+    let name: String
     let parameters: [Parameter]
-    let returnDiscussion: [Text]
+    let resultDiscussion: [Text]
}
```

**Comment by jpsim** [comment]
I'd love to use SourceDeclaration for both Objective-C and Swift since they represent most of the same information. We could also kill off the `Documentation`, `Text` and `Parameter` structs since those aren't really useful anywhere.

**Comment by paulyoung** [comment]
@jpsim would you mind explaining how you anticipate that would be done?

It appears that the existing properties of `SourceDeclaration` are populated via an instance of `CXCursor`, which seems to be specific to Objective-C.

**Comment by jpsim** [comment]
I could foresee a `DeclarationType` protocol that an `ObjCCDeclaration` and `SwiftDeclaration` both conform to. Here's what `SourceDeclaration` currently looks like:

```swift
public struct SourceDeclaration {
    let type: ObjCDeclarationKind
    let location: SourceLocation
    let extent: (start: SourceLocation, end: SourceLocation)
    let name: String?
    let usr: String?
    let declaration: String?
    let documentation: Documentation?
    let commentBody: String?
    var children: [SourceDeclaration]
}
```

Here's how your proposed Substructure could map to this shared `DeclarationType` protocol:

```swift
public struct Substructure {
    let kind: SwiftDeclarationKind    // => DeclarationType.type
    let offset: Int                   // => DeclarationType.offset
    let parsedDeclaration: String     // => DeclarationType.declaration
    let nameLength: Int               // to remove
    let bodyOffset: Int               // to remove
    let bodyLength: Int               // to remove
    let length: Int                   // => DeclarationType.extent
    let doc: Documentation            // => DeclarationType.commentBody
    let name: String                  // => DeclarationType.name
    let typeName: String              // to add to DeclarationType
    let parsedScope: ParsedScope      // => DeclarationType.extent
    let usr: String                   // => DeclarationType.usr
    let nameOffset: Int               // => DeclarationType.location
    let annotatedDeclaration: String? // to remove
    let accessibility: Accessibility? // only in SwiftDeclaration
    let substructure: [Substructure]  // => DeclarationType.children
    let filepath: String              // => DeclarationType.location
}
```

So the `DeclarationType` protocol would look like this:

```swift
protocol DeclarationType {
    var language: Language { get }
    var kind: DeclarationKindType { get }
    var extent: Range<SourceLocation> { get }
    var name: String { get }
    var usr: String { get }
    var declaration: String { get }
    var documentationComment: String? { get }
    var children: [DeclarationType] { get }
}

protocol DeclarationKindType { /* empty protocol */ }
extension ObjCDeclarationKind: DeclarationKindType {}
extension SwiftDeclarationKind: DeclarationKindType {}

enum Language {
    case ObjectiveC
    case Swift
}
```

and the language-specific implementations:

```swift
struct ObjCDeclaration: DeclarationKindType {
    var language: Language { return .ObjectiveC }
    let kind: ObjCDeclarationKind
    /* other DeclarationType members here */
}
struct SwiftDeclaration: DeclarationKindType {
    var language: Language { return .Swift }
    let kind: SwiftDeclarationKind
    /* other DeclarationType members here */
    let accessibility: Accessibility?
}
```

**Comment by paulyoung** [comment]
Makes sense, thanks.

Presumably then `ObjectiveCDeclaration` would have it's properties backed by the instance of `CXCursor`, and `SwiftDeclaration`'s via a dictionary and static methods on `SwiftDocKey`?

**Comment by jpsim** [comment]
More "initialized" by those rather than "backed" but yes.

**Comment by paulyoung** [comment]
Yes :see_no_evil:

**Comment by jpsim** [comment]
Done in #234. Created a new issue to move to typed declarations in #238.
